### ISSUE TITLE
UTF-8 source code, note in attribute list for Emacs editors and some Lisp compilers

### ISSUE THREAD

**Issue by lispm** [phantomics/april#1]
I would propose to put

`;;; -*- coding: utf-8 -*-
`

at the beginning of each UTF-8 file.

This helps some Emacs-like editors to easily recognize that this is an UTF-8 file. The LispWorks compiler also uses this information.

**Comment by phantomics** [comment]
Source files now have attribute lists; are the best practices for entering these attributes codified anywhere? As for the other issues concerning LispWorks I will be testing April with LispWorks soon.
