### ISSUE TITLE
recursive function -- recursive call after power operator?

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#104]
fred isn't a useful function but we can at least define it:
```
      fred←{fred 8,{⍵}⍣0⊢7}
      fred
 ∇fred
```

```
CL-USER> (april "fred←{fred 8,{⍵}⍣0⊢7}")
The value
  𝕊|fred|
is not of type
  SYMBOL
```

i do have a useful function that uncovers the same situation.
my workaround is just to eval this first:
```
fred←{}
```

**Comment by phantomics** [comment]
It compiles now. Can you try the more useful function and see how it works? Send it to me too so I can add it to the tests.

**Comment by justin2004** [comment]
hm, i still had to evaluate my recursive function definition 2 times.

if you run this file in sequence up to this line:
https://github.com/justin2004/advent2020/blob/76fc788a9b8edef5f5c9bba8670b561444a29a02/day8/a.lisp#L41
you'll get 
```
The variable APRIL-WORKSPACE-COMMON::|eval| is unbound.
```
but if you run define my "eval" function a second time then run that line it will work.

**Comment by justin2004** [comment]
my "useful" function is dyadic while the example fred function is monadic... so that might matter?

**Comment by phantomics** [comment]
I tried executing your code, I think the problem is with the code rather than the power operator or recursion. The `adjustacc` variable is not set when the power operator runs for the first time; the line assigning `adjustacc` seems not to run. I tried putting `⎕←'test'` right after the `adjustacc←...` line and no `test` was printed. If you have time give it a look and see if you can find why `ajdustacc` isn't getting assigned.

**Comment by justin2004** [comment]
i think in that code i made some assumptions that relied on the old nested model.
because i can get it to work if i switch back to master and throw in a 
```
(april "eval←{}")
```

i'll see if i can pinpoint it later today.

**Comment by justin2004** [comment]
even if i hardcode adjustacc to a number (operate-to-power) still sees NIL.

**Comment by phantomics** [comment]
This should work as a miminal reproduction of this bug. Does this code behave the same way for you?

```lisp
(april "
  stuff←{ $[0=⊃⍵; 1↓⍵; ⍺ stuff (⊃(⍵-1)),{⎕←⍺×⍵+3}⍣(⊃⍵)⊢1↓⍵] }
  2 stuff 3 4 5 6
")
```

**Comment by justin2004** [comment]
```
JUSTIN> (april "stuff←{ $[0=⊃⍵; 1↓⍵; ⍺ stuff (⊃(⍵-1)),{⎕←⍺×⍵+3}⍣(⊃⍵)⊢1↓⍵] }
                       2 stuff 3 4 5 6
                       ")
7 8 9
10 11 12
13 14 15
The variable APRIL-WORKSPACE-COMMON::|stuff| is unbound.
   [Condition of type UNBOUND-VARIABLE]
   
JUSTIN> (april "stuff←{ $[0=⊃⍵; 1↓⍵; ⍺ stuff (⊃(⍵-1)),{⎕←⍺×⍵+3}⍣(⊃⍵)⊢1↓⍵] }
                       2 stuff 3 4 5 6
                       ")
7 8 9
10 11 12
13 14 15
16 17 18
19 20 21
22 23 24
#(22 23 24)
```

**Comment by phantomics** [comment]
This is now working correctly, a pre-compile stage is needed to make sure the symbols of self-referencing functions are properly initialized. As an added bonus, defined operator self-reference has also been enabled. For example:

```lisp
* (april "rlop←{$[⍵<2000; ⍵,⍺⍺ ∇ 3 ⍺⍺ 2×2+⊃⍵; ⍵]} ⋄ × rlop 5")
#(5 42 264 1596 9588)
```
