### ISSUE TITLE
hydrant each

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#105]
```
      +/⍎¨'123' '456' '99'
678
```

```
CL-USER> (april "+/⍎¨'123' '456' '99'")
The function COMMON-LISP:NIL is undefined
```

a workaround:
```
CL-USER> (april "+/{⍎⍵}¨'123' '456' '99'")
678
```

**Comment by phantomics** [comment]
Good catch, hydrant is a special lexical form in April so it doesn't work with `¨` but it should be possible. Stay tuned.

**Comment by phantomics** [comment]
This is now working, try `(april "⍎¨'1+1' '2+2' '3+3'")`.
