### ISSUE TITLE
Incorrect grade on character array

### ISSUE THREAD

**Issue by gmfawcett** [phantomics/april#11]
On SBCL 1.5.6, on Linux 4.4.0/x86_64, with April 20191227 (from Quicklisp):

    CL-USER> (ql:system-apropos "april")
    #<SYSTEM aplesque / april-20191227-git / quicklisp 2019-12-27>
    #<SYSTEM april / april-20191227-git / quicklisp 2019-12-27>
    #<SYSTEM vex / april-20191227-git / quicklisp 2019-12-27>
	
	CL-USER> (april:april "s←'abcABC012xyzXYZ789'⋄s[⍋s]")
    "ABCXYZabcxyz012789"
	
Compare with Dyalog or GNU APL:

          s←'abcABC012xyzXYZ789'⋄s[⍋s]
    012789ABCXYZabcxyz

`(april:april (test))` is passing correctly, and numeric arrays are grading correctly:

    CL-USER> (let ((s (map 'vector 'char-code "abcABC012xyzXYZ789")))
      (map 'string 'code-char
           (april:april (with (:state :in ((s s)))) "s[⍋s]")))
    "012789ABCXYZabcxyz"

**Comment by phantomics** [comment]
Good catch, the grading is according to the *atomic-vector* defined in spec.lisp. I'm not sure why I originally put the digits after the letters in there but it's been fixed.

**Comment by gmfawcett** [comment]
Great, thank you!  And thanks for April, I'm having fun playing with it.
