### ISSUE TITLE
intermittent eval trouble

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#114]
this always evals quickly before commit 6dcaf7adc9084fee5c898fc88af7c00aa28ea41e:
```
CL-USER> (april "'.'=¨'one' 'two.' 'three         ' 'four'")
#(#0A#(0 0 0) #0A#(0 0 0 1) #0A#(0 0 0 0 0 0 0 0 0 0 0 0 0 0) #0A#(0 0 0 0))
```

but at this commit
```
commit 6dcaf7adc9084fee5c898fc88af7c00aa28ea41e (HEAD, refs/bisect/bad)
Author: phantomics <a@imagegardenphoto.com>
Date:   Mon Dec 21 20:30:28 2020 -0800

    parallelized ↑↓⍴⍳/⌿\⍀¨, choose, scalar op
```

it sometimes does not ever finish evaluating. it just seems to hang.

**Comment by phantomics** [comment]
Parallelism in operators was causing a problem, since those operators can take functions that are also parallelized. The operators are single-threaded again while I investigate fixes.
