### ISSUE TITLE
rank with vector

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#117]
i haven't been able to get it to do anything interesting but it does do something in dyalog:
```
      M←10 10 ⍴ 0 ⋄ M[3;4]←1 ⋄ M[3;1]←1
      2 (+⍤0 1)M
2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
3 2 2 3 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
2 2 2 2 2 2 2 2 2 2
```

```
CL-USER> (april "M←10 10 ⍴ 0 ⋄ M[3;4]←1 ⋄ M[3;1]←1")                
NIL
CL-USER> (april "2(+⍤0 1)M")
The value
  #(0 1)                                                            
is not of type
  NUMBER
  ```

**Comment by justin2004** [comment]
on aplcart.info

```
Mv(f⍤0 1)Nm              Apply f between vector Mv and each column of Nm
```
but i don't think i have been able to get it to do that?

**Comment by phantomics** [comment]
Here's how to use it. Try `(⍳3)+⍤1⊢3 3⍴5` and see that the vector is added to each row. Try `(⍳3)+⍤0 1⊢3 3⍴5` and see that the vector is added to each column. I'll get it in soon.

**Comment by phantomics** [comment]
Good news, the above cases now work. April now supports a vector of up to 3 elements as the right operand for `[⍤ rank]`, like Dyalog. Let me know if you find any more problems with it.
