### ISSUE TITLE
outer product involving axis

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#120]
in april this
```
CL-USER> (april-f "(1 2 3) (2 3 4) ∘.⌽[1] ⊂3 3 ⍴ ⍳9")
 4 8 3  7 2 6
 7 2 6  1 5 9
 1 5 9  4 8 3
#(#2A((4 8 3) (7 2 6) (1 5 9)) #2A((7 2 6) (1 5 9) (4 8 3)))
```

behaves like this in dyalog:
```
      (1 2 3) (2 3 4) ∘.(⌽[1]) ⊂3 3 ⍴ ⍳9
 4 8 3  7 2 6 
 7 2 6  1 5 9 
 1 5 9  4 8 3
```

in dyalog you need those parens:
```
      (1 2 3) (2 3 4) ∘.⌽[1] ⊂3 3 ⍴ ⍳9
SYNTAX ERROR
      (1 2 3)(2 3 4)∘.⌽[1]⊂3 3⍴⍳9
```

but when you add the parens in april:
```
CL-USER> (april-f "(1 2 3) (2 3 4) ∘.(⌽[1]) ⊂3 3 ⍴ ⍳9")
 2 3 1  3 1 2
 6 4 5  4 5 6
 7 8 9  8 9 7
#(#2A((2 3 1) (6 4 5) (7 8 9)) #2A((3 1 2) (4 5 6) (8 9 7)))
```
it seems to ignore the axis.

**Comment by phantomics** [comment]
Not sure why Dyalog needs the parens, there doesn't seem to be any ambiguity without them. I need to enable currying axes with functions in parens, that's coming soon.

**Comment by phantomics** [comment]
The axis in parens now works, but I'm going to research some to see why parens are needed in Dyalog.

**Comment by phantomics** [comment]
It doesn't seem there's a solid reason for parens being needed in Dyalog, I see no ambiguity as to what the axis is applied to, it couldn't be the function produced by `∘.⌽` since outer-producing functions can't take axes. I'm calling this fixed for now.
