### ISSUE TITLE
comment as last expression in defn

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#125]
very low priority...

i don't know how to load .apl files in dyalog so i can't see how dyalog handles this but i would expect this function call to evaluate to 5
```
JUSTIN> (april "fun←{5                                             
             ⍝2                                                    
             }")                                                   
#<FUNCTION (LAMBDA (APRIL::⍵ &OPTIONAL APRIL::⍺)) {53311A5B}>      
JUSTIN> (april "fun 0")                                            
NIL
```

**Comment by abrudz** [comment]
Indeed, that'll give 5. [Try it online!](https://tio.run/##SyzI0U2pTMzJT///P60071HbhGpTBVIA16PeuUYKZACuWrCNCgYA "APL (Dyalog Unicode) – Try It Online")

**Comment by justin2004** [comment]
thanks for the confirmation, @abrudz .

and also thanks for making that javascript APL keyboard! i used it for a little class i taught:
https://github.com/justin2004/image-filtering

the students liked your keyboard.

**Comment by phantomics** [comment]
Good catch, this is now fixed.
