### ISSUE TITLE
⎕AV

### ISSUE THREAD

**Issue by abrudz** [phantomics/april#126]
https://github.com/phantomics/april/blob/master/environmental-symbols.md#system-constants says that `⎕AV` is used by `⍋` and `⍒` and `⍸` but this is only the case in "legacy" APLs, e.g. Dyalog APL Classic. In modern versions, like Dyalog APL Unicode and GNU-APL, `⎕AV` is ignored and Unicode code points are used instead.

I would strongly recommend following Unicode, especially since relying on `⎕AV` requires choosing one 256-character set out of a large number of legacy APL encodings, and also doesn't provide useful ordering of characters not in `⎕AV`.

**Comment by phantomics** [comment]
Thanks for the tip, I'll change that once I'm done with some function optimizations.

**Comment by phantomics** [comment]
`⎕AV` is out and `⍋⍒⍸` now use Unicode code points in any Common Lisp implementation supporting Unicode, which is required to use April in the first place.
