### ISSUE TITLE
clear a workspace

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#137]
```
APRIL> (april-create-workspace space2)
"Successfully created workspace ｢SPACE2｣."
APRIL> (april (with (:restore-defaults) (:space space2))) 
The function :RESTORE-DEFAULTS is undefined.
   [Condition of type UNDEFINED-FUNCTION]
```

**Comment by phantomics** [comment]
`(:restore-defaults)` was deprecated when I changed the workspace model a while ago, thanks for noticing that. You can use a macro called `(april-clear-workspace)` to do what you want, it's as simple as `(april-clear-workspace space2)`. The docs have been updated as well.
