### ISSUE TITLE
(:store-fun) and each

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#139]
it works the second time:
```
APRIL> (april (with (:store-fun (charlie #'(lambda (&rest x) 0))))
       "charlie¨5 6 7")
The function COMMON-LISP:NIL is undefined.
   [Condition of type UNDEFINED-FUNCTION]
APRIL> The task was killed.               
   [Condition of type TASK-KILLED-ERROR]  
APRIL> (april (with (:store-fun (charlie #'(lambda (&rest x) 0))))
       "charlie¨5 6 7")
#(0 0 0)
APRIL>
```

**Comment by phantomics** [comment]
Good catch, that'll happen when you try using an operator with any function you've just stored. I often use `:store-fun` in an invocation by itself at the top of a file, then run the actual April code or load it from .apl files. I'll see what if there's a straightforward way to make this work.

**Comment by phantomics** [comment]
This is fixed.
