### ISSUE TITLE
operator side effects

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#142]
i don't think this is an april bug because april's behavior is what i'd expect:

```
APRIL> (april "3 +{⍺ ⍺⍺ ⍵⋄⍺ ⍵⍵ ⍵}÷ 4")
3/4
```
that is -- the operator evaluates to the last expression.

but dyalog doesn't seem to allow operators to have side effect expressions like that:
```
      3 +{⍺ ⍺⍺ ⍵⋄⍺ ⍵⍵ ⍵}÷ 4
7
```
it stops at the first expression.

just wanted to bring it to your attention since they are different behaviors.

**Comment by phantomics** [comment]
This doesn't just affect operators. Try `{2 ⋄ 1+⍵} 3` and you get 2. That's because in a defn or inline operator, the first non-assignment is returned. I'm considering how to deal with this, like you I prefer April's way of doing it.

**Comment by phantomics** [comment]
So here's what I've learned. Having defns return the first non-assigning statement was the doing of John Scholes, who implemented Dyalog's defns. He wanted defns to be used only for purely functional programming. I see functional programming as the ideal for APL but one that sometimes must be compromised, so I'd rather users be able to write side-effecting code in defns. Nothing is lost by allowing it and it's more intuitive and simpler to implement. April's model for user-defined functions and operators will remain as it is.

**Comment by justin2004** [comment]
sounds good to me!
