### ISSUE TITLE
Excessive consing during reduction over axis

### ISSUE THREAD

**Issue by egao1980** [phantomics/april#15]
I'm trying April as a tool for image processing. I understand that currently performance is not the main focus but I think it would be nice to have.

Loading image:

```lisp
OPTICL-OCR> (defparameter *img* (opticl:read-png-file #p"tests/data/in.png"))
*IMG*
``` 
As an array of unsigned bytes:

```lisp
#<(SIMPLE-ARRAY (UNSIGNED-BYTE 8) (2485 3500 3)) {10080C7D2F}>
--------------------
Dimensions: (2485 3500 3)
...
```
And then converting it to grayscale (upto / 3):

```lisp
OPTICL-OCR> (ql:quickload :april)
To load "april":
  Load 1 ASDF system:
    april
; Loading "april"
..
Specified idiom ｢APRIL｣ with 3 basic grammar elements, 4 opening grammar patterns, 7 following grammar patterns, 97 lexical functions, 14 lexical operators, 14 utility functions and 485 unit tests.

(:APRIL)
OPTICL-OCR> (time (april:april (with (:state :in ((a *img*))))
                               "+/[3] a"))
Evaluation took:
  8.437 seconds of real time
  8.437500 seconds of total run time (8.218750 user, 0.218750 system)
  [ Run times consist of 0.657 seconds GC time, and 7.781 seconds non-GC time. ]
  100.01% CPU
  23 lambdas converted
  28,678,250,025 processor cycles
  7,533,410,064 bytes consed
```

Consing 7Gb while only 8.6Mb is needed in ideal case.

**Comment by egao1980** [comment]
I think that we can use arrays (because it's APL :)) for passing transient coordinates to functions in like across / do-over so the same array instance would be reused for iteration.

**Comment by phantomics** [comment]
I've done some optimization of the (across) and (do-over) functions. I considered using arrays to pass coordinates in the past, but it isn't a good choice because the coordinates have to be fed to (apply), for example: `(apply #'aref output coords)`. If the coordinates are stored in array you have to loop across the array and collect them into a list to be passed to (apply). Instead, I now use a list to store coordinates and reset its element values instead of consing new elements while iterating over arrays. If you can think of a better way to do this I'm all ears.

**Comment by phantomics** [comment]
Also, a tip: if you want a simpler way to pass variables into April, you can use the (april-c) macro. For example:

```lisp
(april:april-c "{+/[3]⍵}" *img*)
```

You can use an `⍺` argument too (the second argument to (april-c) becomes `⍺`), or if you want more than 2 arguments, you can use the k-style n-argument functions using the syntax shown here: [Unique Language Features](https://github.com/phantomics/april#unique-language-features-in-april). As in:

```lisp
* (april:april-c "{[a;b;c]a+b×c}" 5 6 7)
47
```

**Comment by egao1980** [comment]
Thanks. There's a reference to ```across-3``` function in code - just a small issue.

I've found that adding (declare (dynamic-extent [w|e]coords)) to all the places greatly reduces consing on SBCL.

Before:

```lisp 
CL-USER> (time (april:april (with (:state :in ((a (compute (reshape 1.0 (~ 0 1000 ~ 0 1000 ~ 0 3))))))) "+/[3] a"))
Evaluation took:
  1.292 seconds of real time
  1.296875 seconds of total run time (1.203125 user, 0.093750 system)
  [ Run times consist of 0.108 seconds GC time, and 1.189 seconds non-GC time. ]
  100.39% CPU
  84 lambdas converted
  4,393,922,525 processor cycles
  1,144,924,832 bytes consed
```

After:

```lisp
CL-USER> (time (april:april-c "{+/[3]⍵}" (compute (reshape 1.0 (~ 0 1000 ~ 0 1000 ~ 0 3)))))
Evaluation took:
  1.095 seconds of real time
  1.093750 seconds of total run time (1.062500 user, 0.031250 system)
  [ Run times consist of 0.078 seconds GC time, and 1.016 seconds non-GC time. ]
  99.91% CPU
  3,722,811,884 processor cycles
  36,137,664 bytes consed
```

**Comment by phantomics** [comment]
Many functions in april/aplesque and april/library.lisp have been revised to reduce consing, and dynamic-extent declarations have been added as well. What does your performance look like now?

**Comment by egao1980** [comment]
Looks much better.  Similar to what I had. 

For the interpreted april/aplesque:

```lisp
CL-USER> (time (april:april (with (:state :in ((a (compute (reshape 1.0 (~ 0 1000 ~ 0 1000 ~ 0 3))))))) "+/[3] a"))
Evaluation took:
  1.030 seconds of real time
  1.031250 seconds of total run time (1.031250 user, 0.000000 system)
  [ Run times consist of 0.016 seconds GC time, and 1.016 seconds non-GC time. ]
  100.10% CPU
  84 lambdas converted
  3,501,742,567 processor cycles
  38,822,832 bytes consed
```

Compilled to fasl: 

```lisp
CL-USER> (time (april:april (with (:state :in ((a (compute (reshape 1.0 (~ 0 1000 ~ 0 1000 ~ 0 3))))))) "+/[3] a"))
Evaluation took:
  1.033 seconds of real time
  1.031250 seconds of total run time (1.031250 user, 0.000000 system)
  [ Run times consist of 0.032 seconds GC time, and 1.000 seconds non-GC time. ]
  99.81% CPU
  3,508,134,522 processor cycles
  36,072,128 bytes consed
```

**Comment by egao1980** [comment]
On a 4k image:

```lisp
CL-USER> (defparameter *img* (opticl:read-png-file #p"tests/data/in.png"))
*IMG*
CL-USER> (time (april:april-c "{+/[3]⍵}" *img*))
Evaluation took:
  7.197 seconds of real time
  7.203125 seconds of total run time (7.187500 user, 0.015625 system)
  [ Run times consist of 0.093 seconds GC time, and 7.111 seconds non-GC time. ]
  100.08% CPU
  24,463,596,515 processor cycles
  156,555,568 bytes consed
```

**Comment by egao1980** [comment]
Consing seems to be reasonable for now. We can improve it more later. CPU cycles are next target :)

**Comment by phantomics** [comment]
All right, CPU usage is a topic separate from this issue so I've emailed you if you'd like to discuss it in detail. Work on consing will finish for now.
