### ISSUE TITLE
stencil: rectangle size bigger than Y -- (f⌺g)Y

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#158]
```
      ⊢⌺3 3⊢2 2 ⍴ ⍳14
0 0 0
0 1 2
0 3 4
     
0 0 0
1 2 0
3 4 0
     
     
0 1 2
0 3 4
0 0 0
     
1 2 0
3 4 0
0 0 0
```

```
APRIL> (april "⊢⌺3 3⊢2 2 ⍴ ⍳12")
Invalid index 4 for (SIMPLE-ARRAY (UNSIGNED-BYTE 4) (2 2)), should be a non-negative integer below 4.
   [Condition of type SB-INT:INVALID-ARRAY-INDEX-ERROR]
```

**Comment by phantomics** [comment]
I've restored the original non-parallel implementation of `⌺`. The new parallel function was causing the first 3 of your stencil problems, the last one I'm not sure about. I'll fix the parallel `⌺` later but let me know if this allows you to port the box function.

**Comment by justin2004** [comment]
we don't need stencil for the box function. i was just learning/exploring stencil too.
i can really speed up my sobel edge detector implementation with it!

**Comment by phantomics** [comment]
This is fixed. However, I'm still unsure of some of `⌺`'s implementation details so if you'd like to test it more it'd help.

**Comment by justin2004** [comment]
will do.
