### ISSUE TITLE
immutability -- value type vs reference type

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#161]
this may be a design decision...

dyalog does value type
```
      a←1 2 ⋄ b←a ⋄ b[2]←5 ⋄ a b
 1 2  1 5
```

april does reference type
```
APRIL> (april "a←1 2 ⋄ b←a ⋄ b[2]←5 ⋄ a b")                         
#(#(1 5) #(1 5))
```

**Comment by justin2004** [comment]
i wonder what other APLs do... because this could make porting code have some sneaky bugs if you aren't aware of this

**Comment by justin2004** [comment]
gnu apl:
```
a←1 2 ⋄ b←a ⋄ b[2]←5 ⋄ a b
 1 2  1 5
```

**Comment by phantomics** [comment]
Good observation, I'll check and see if assignment by reference is a standard in APL.

**Comment by phantomics** [comment]
Variables are now always assigned by value.

**Comment by justin2004** [comment]
wow, it was really helpful to do all assignments in (apl-assign) -- which made this change quick!

i assumed assignment would have been done all over.
