### ISSUE TITLE
stencil: vector left argument given to f  -- (f⌺g)Y

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#162]
stencil should give f (, in this case) the number of fill elements (with the sign indicating before or after (+ is before and - is after)) as the left argument:
```
      ,⌺5  ⊢⍳6
 2 0 0 1 2 3
 1 0 1 2 3 4
 0 1 2 3 4 5
 0 2 3 4 5 6
¯1 3 4 5 6 0
¯2 4 5 6 0 0
```

april almost gets the side of the fill elements correct but not the amount of fill elements:
```
APRIL> (april ",⌺5  ⊢⍳6")
#2A((1 0 0 1 2 3)
    (0 0 1 2 3 4)
    (0 1 2 3 4 5)
    (0 2 3 4 5 6)
    (0 3 4 5 6 0)
    (-1 4 5 6 0 0))
```

**Comment by phantomics** [comment]
Fixed.
