### ISSUE TITLE
stencil

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#168]
```
      +/,{+/+/⍵}⌺3 3⊢5 5 ⍴ ⍳5
507
      +/,{+/+/⍵}⌺3 3⊢6 5 ⍴ ⍳5
624
```

```
APRIL> (april "+/,{+/+/⍵}⌺3 3⊢5 5 ⍴ ⍳5")
507
APRIL> (april "+/,{+/+/⍵}⌺3 3⊢6 5 ⍴ ⍳5")
616
```

**Comment by justin2004** [comment]
you can see where the elements start to diverge (at the end of the first row i think) with
```
⊢⌺3 3⊢6 5 ⍴ ⍳5
```

**Comment by phantomics** [comment]
Pinpointed the problem, it's in the part I thought may not be flawed before. Figuring out a definitive fix.

**Comment by phantomics** [comment]
Fixed, the problem I suspected before has been corrected.

**Comment by justin2004** [comment]
i just used stencil do do sobel edge detection and it works great!

**Comment by phantomics** [comment]
Excellent, did you say you'd implemented sobel edge detection without stencil before? I'd be interested to compare the speed of the two algorithms.

**Comment by justin2004** [comment]
yup. i'll make a repo and put both versions in. 
night and day.
