### ISSUE TITLE
dyadic transpose [feature request]

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#175]
to get the main diagonal from a matrix:
```
      1 1 ⍉ 5 5 ⍴ ⍳25
1 7 13 19 25
```

```
JUSTIN> (april-f "1 1⍉5 5 ⍴ ⍳ 25")
Condition ARRAY-OPERATIONS/TRANSFORMING:PERMUTATION-REPEATED-INDEX was signalled.
   [Condition of type PERMUTATION-REPEATED-INDEX]
```

**Comment by phantomics** [comment]
This functionality has been added but the implementation could use work, it's not the most efficient. Give it a try, and try with higher-dimensional arrays too, like `2 2 1⍉2 3 4⍴⍳24`. The `⍉` function is now implemented in parallel as well, I'm seeing about a 5x speed increase for permuting large arrays.

**Comment by phantomics** [comment]
I've worked out all the bugs I could find in the diagonal `⍉` functionality and it's fully parallelized as well. If you find any problems with it let me know.
