### ISSUE TITLE
scalar extension with catenate not working on characters

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#18]
`(april "(2 2 ⍴ 5),6 6")`
works as expected

`(april "(2 2 ⍴ 5),6")`
same result as the previous due to scalar (6) being extended, as expected

now with character data

`(april "(2 2 ⍴ 'h'),'**' ")`
works as expected

`(april "(2 2 ⍴ 'h'),'*' ")`
signals "Incompatible arrays."

**Comment by phantomics** [comment]
Good catch, turns out I was reading single characters like '*' as one-element vectors rather than scalars. That's fixed now.
