### ISSUE TITLE
Random floating-point numbers with `?` primitive

### ISSUE THREAD

**Issue by abvbv** [phantomics/april#181]
Hello, Andrew!

I'm trying to generate an array of random floating-point numbers in April.

Dyalog APL [allows](https://help.dyalog.com/latest/#Language/Primitive%20Functions/Roll.htm) 0 as the right argument to `?`:

> For each zero element of Y, the corresponding element of R is a pseudo-random floating-point value in the range 0 - 1, but excluding 0 and 1, i.e. (0<R[I]<1).

At the same time, Common Lisp's [`random`](http://www.lispworks.com/documentation/lw50/CLHS/Body/f_random.htm), which April uses to implement `?` (AFAIU), accepts a _positive float_ as an argument to generate floats.

But April's `?` [expects](https://github.com/phantomics/april/blob/bc855168aa570925d9aa366eca97218d8b144575/spec.lisp#L288-L293) only _integers_ as the right argument, so it looks like there's no way to generate floating-point numbers in April.

I'd expect `(april-c "? 0")` to behave exactly as in Dyalog APL.

`(random 1.0)` is similar to that, but it does return 0 sometimes, unlike `?` in Dyalog APL.

Just a question: do you think it's wrong from the language design point of view for `?` to accept both integers and floats? It'll introduce incompatibility with other APLs, but April already has some distinctive features.

**Comment by phantomics** [comment]
Thanks for pointing this out. `?0` will now work approximately as in Dyalog. The minimum value is the `double-float-epsilon` and the maximum value is 1.0 - the epsilon. Also, you can now pass floats to `?`. It's different from other APLs but they throw an error when you give floats to `?`  so it wouldn't break anything ported over from those implementations. Let me know how it works for you.

**Comment by abvbv** [comment]
Looks good. Thank you for the fix!

> `(error "The right arguments to ? must be non-negative integers.")`

Maybe the error message needs to mention floats too.

**Comment by phantomics** [comment]
I thought I'd changed the error message, it's updated now.
