### ISSUE TITLE
Why does `where-equal-to-one` return 0 and not an empty vector `#()`?

### ISSUE THREAD

**Issue by abvbv** [phantomics/april#182]
I thought code like `(april:april-f "⍸ 0")` would return an empty vector, but it [returns](https://github.com/phantomics/april/blob/c4f237a474074b451040bb94e52db6bad04cfab0/library.lisp#L213) just a number. What's the motivation?

**Comment by justin2004** [comment]
dyalog doesn't return a number:
```
      ⍸0

 
```

looks like a bug

**Comment by phantomics** [comment]
This was a bug, now fixed. Good catch.
