### ISSUE TITLE
quote balance is permissive

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#188]
```
APRIL> (april "(⍳4) {⍺ '_ ⍵} ⍳4")
#(#(1 2 3 4) "_ ")
```

```
      (⍳4) {⍺ '_ ⍵} ⍳4
SYNTAX ERROR
      (⍳4){⍺ '_ ⍵} ⍳4
                      ∧
```

**Comment by phantomics** [comment]
This and the paren issue are fixed, thanks for finding them. There was a balance checker for (), [] and {} before but I made a change that disabled it at some point. I've also finished some comprehensive reworking of the mechanics for compiling function calls, including a new system for selective assignment (like `(3↑x)←5`) that adds many improvements. I'm checking off the last few to-dos before a release, let's connect on IRC when you can.
