### ISSUE TITLE
Key behavior discrepancy 

### ISSUE THREAD

**Issue by carkat** [phantomics/april#189]
Key's optional left argument in Dyalog groups major cells by keys in the left argument. From the Dyalog docs included with version 18. 

> `R←{X}f⌸Y` If X is specified, it is an array whose major cells specify keys for corresponding major cells of Y. The Key operator ⌸ applies the function f to each unique key in X and the major cells of Y having that key.

The following example groups even and odd "rows", rows being the major cell in a 2d matrix
```apl
    {(2|⍳≢⍵)⊢⌸⍵}10 2⍴⍳20
 1  2
 5  6
 9 10
13 14
17 18
     
 3  4
 7  8
11 12
15 16
19 20
```

In April, this behavior seems to only apply to sequential individual cells. 
```apl
    {⎕←(2|⍳≢⍵)⊢⌸⍵}10 2⍴⍳20
0 2 4 6 8
1 3 5 7 9
```

This can be fixed manually with the following:
```apl
    {⎕←↑(2|⍳≢⍵)⊢⌸↓⍵}10 2⍴⍳20
 1  2
 5  6
 9 10
13 14
17 18
     
 3  4
 7  8
11 12
15 16
19 20
```

**Request:** April's key with left argument X apply grouping to major cells of right argument Y

**Comment by phantomics** [comment]
This should be fixed, give it a try and let me know.

**Comment by carkat** [comment]
Works as described, thanks!
