### ISSUE TITLE
dyadic ⊂  behaves different than GNU APL

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#19]
in gnu apl
` 1 1 2 2 ⊂ ⍳4`
evaluates to ` 1 2  3 4` (a 2 item vector with the partition between the 2 and 3)

(april "⎕←1 1 2 2⊂⍳4")
also evaluates to a 2 item vector but the partition is between the 1 and 2: ` 1  2 3 4` 

also dyalog (https://tutorial.dyalog.com/) expects the former.

thanks for recommending dyalog's tutorial (in your video on april), by the way!

**Comment by justin2004** [comment]
also april is behaving different with row-wise and column-wise partitioned enclosure 
e.g.
`1 1 2 2 2 ⊂[1] 5 3⍴⍳15`

**Comment by phantomics** [comment]
No need for different issues. What you're encountering is the difference between the Dyalog APL lexicon and the IBM APL2 lexicon (GNU is based on APL2). To get the effect you want, enter `1 1 2 2 ⊆ ⍳4`. The `⊆` character represents the partition function in Dyalog APL and the `⊂` character represents partitioned enclose. April is based off of Dyalog APL more closely than APL2.

I know you tried it with the tutorial and it didn't work, the funny thing is that the Dyalog APL running the tutorial is in a mode where its lexicon is closer to that of APL2 than that of standard Dyalog. Dyalog has a variable `⎕ML` (for "migration level") that you can set to determine how closely you'd like your Dyalog lexicon to mirror APL2.

If you [download Dyalog APL](https://www.dyalog.com/download-zone.htm?p=download) and try it out on your computer you'll find that it works the same was as in April. By the way, the online tutorial is great for learning but [TryAPL.org](https://tryapl.org/) is better for testing APL code on the web. Both it and the tutorial have a high "migration level" toward APL2 and you can't reset the `⎕ML` variable in their REPLs.

The readme file has been updated to explain the lexical difference between April and other APLs. Also, your question prompted me to check out the functionality if `⊂` and I found some bugs and fixed them, so thanks.

**Comment by justin2004** [comment]
i hadn't heard of this "migration level." interesting.
thanks for the clarification!

i'll start running dyalog locally too (instead of just using their tutorial interpreter).
