### ISSUE TITLE
operator completes the train but maybe should throw an error

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#192]
while looking for this
```
(april "(2⊃⊢)¨ '123' '456' '789'")
```

i noticed this:
```
APRIL> (april "(2⊃¨) '123' '456' '789'")
#(#\1 #\4 #\7)
```

but in dyalog:
```
      (2⊃¨) '123' '456' '789'
SYNTAX ERROR: Missing right argument
      (2⊃¨)'123' '456' '789'
        ∧
```

since the ¨ operator should fuse with the ⊃ the error is basically of this form i think:  
```
      (2+) 5
SYNTAX ERROR: Missing right argument
      (2+)5
        ∧
```

**Comment by phantomics** [comment]
April now has a completely new compiler core. As well as being much faster it also completely fixes this issue; both of the above examples will throw an error.
