### ISSUE TITLE
shape after catenenate with axis

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#195]
```
CL-USER> (april-f "⍴,[2] 2 2 3⍴⍳12")
12
12
```

```
      ⍴,[2] 2 2 3⍴⍳12
2 2 3
```

but with an intermediate assignment it works
```
CL-USER> (april "b←,[2] 2 2 3⍴⍳12")
#3A(((1 2 3) (4 5 6)) ((7 8 9) (10 11 12)))
CL-USER> (april "⍴b")
#(2 2 3)
```

**Comment by phantomics** [comment]
This is because of the optimization pattern for `⍴,` that gets the total size of the array. Stand by while I find a fix for this.

**Comment by phantomics** [comment]
This is now fixed. Also just added a bunch of stuff including demos for the Dyalog tree functions: 

https://github.com/phantomics/april/blob/master/demos/dfns/tree/tree.apl

https://github.com/phantomics/april/blob/master/demos/dfns/tree/demo.lisp

Release is coming soon. I've got almost all features working across different CL implementations, there are some annoyances around rational/float conversion and a trig function in ECL but that's about it.
