### ISSUE TITLE
strand notation with indexing first

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#197]
```
      la←5 6 7 ⋄ la[1 3] 'apple'
┌───┬─────┐
│5 7│apple│
└───┴─────┘
```

```
APRIL> (april "la←5 6 7 ⋄ la[1 3] 'apple'")
Invalid index 2 for (SIMPLE-VECTOR 2), should be a non-negative integer below 2.
   [Condition of type SB-INT:INVALID-ARRAY-INDEX-ERROR]
```

another case (april lost the 8) :
```
APRIL> (april "la←5 6 7 ⋄ la[1 3] 8 9")
#(#(5 6 7) 9)
```
oh and it did the indexing incorrect too

**Comment by phantomics** [comment]
This is fixed.

**Comment by jaccarmac** [comment]
I may be misunderstanding something about April's branch, but something about stranding seems to remain broken in that context.

```
CL-USER> (april:april "x←1 ◊ 3→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
1155
CL-USER> (april:april "x←1 ◊ (3)→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
1155
CL-USER> (april:april "x←1 ◊ (⊢3)→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
7
```

**Comment by justin2004** [comment]
in dyalog:
```
      x←1 ◊ 3→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7
NOT PERMITTED: Illegal token
      x←1 ◊3→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7
     ^  
```

**Comment by jaccarmac** [comment]
I don't think that's unexpected. The example from `(demo)` also fails in Dyalog, since this form of branch is novel.

```
x←1 ⋄ (3-2)→two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7
NOT PERMITTED: Illegal token
      x←1 ⋄ (3-2)→two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7
           ^
```

**Comment by justin2004** [comment]
i didn't even know april supported branch (→).

> I'm not sure what the significance of the difference in output is.

i don't think april intends to deviate from dyalog in assignment and strand notation.
since i didn't know about branch i am not sure if april intends to deviate from dyalog with that but i assume it does not. so that is the significance of the difference in the output. that is, april should probably throw an error for those expressions like dyalog does.

**Comment by justin2004** [comment]
ah, feel free to ignore me:
```
The biggest difference between April and other APLs lies in its implementation of the → branch function
```
i never noticed that.

**Comment by jaccarmac** [comment]
To be fair, the connection to this issue may be a red herring and I left out the example suggesting that connection.

```
CL-USER> (april:april "x←1 ◊ 3→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
1155
CL-USER> (april:april "x←1 ◊ 3→one two three four ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
7
```

**Comment by phantomics** [comment]
Justin got it right, the branch implementation in April is different from Dyalog. the examples jaccarmac posted above are working correctly. I didn't like that the traditional branch convention where you would write `one→` has nothing to the right of the →, whereas typically in APL every function or operator character must have something to its right.

By the way jaccarmac I see you like roguelikes, generating levels for a tile-based game would be an interesting application of APL.

**Comment by justin2004** [comment]
> By the way jaccarmac I see you like roguelikes, generating levels for a tile-based game would be an interesting application of APL.

totally!

**Comment by jaccarmac** [comment]
> ...the examples jaccarmac posted above are working correctly.

If it's not too much trouble, can you elaborate on that? Based on my reading of the grammar and intuition about the function of branch, these three things should return the same result.

```
CL-USER> (april:april "x←1 ◊ 3→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
1155
CL-USER> (april:april "x←1 ◊ (⊢3)→one two three ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
7
CL-USER> (april:april "x←1 ◊ 3→one two three four ⋄ x×←11 ⋄ one→⎕ ⋄ x×←3 ⋄ two→⎕ ⋄ x×←5 ⋄ three→⎕ ⋄ x×←7")
7
```

(possibly relevant comments from `complete-branch-composition`)

https://github.com/phantomics/april/blob/401fbfc8e77a1c3c78b8920a210c8b54e56e3fc7/grammar.lisp#L895-L897
https://github.com/phantomics/april/blob/401fbfc8e77a1c3c78b8920a210c8b54e56e3fc7/grammar.lisp#L901-L902

> By the way jaccarmac I see you like roguelikes, generating levels for a tile-based game would be an interesting application of APL.

I agree! I'm working my way through Advent of Code in April this year, and think there are some problems in that vein in my future.

**Comment by phantomics** [comment]
Oops, you're right, there is a bug there. All of your examples should go to the `three→⎕` point. I thought you were copying from the tests and kind of glazed over the code, been busy with a Bloxl exhibition. I'm reopening the issue and will check this out, look for something after Christmas.

**Comment by phantomics** [comment]
This is new fixed, good job finding it.
