### ISSUE TITLE
strand/vector assignment might not be implemented

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#20]
`(april "(a b c)←1 2 3")`
signals an error: (𝕊|a| 𝕊|b| 𝕊|c|) is not a string designator

but in gnu apl and in the dyalog tutorial the vector `1 2 3` is destructured item-wise into a b and c.

**Comment by phantomics** [comment]
You're right, it's not yet implemented. I'll give it a try later.

**Comment by phantomics** [comment]
It's working, that was easier than expected. Try it out.

**Comment by justin2004** [comment]
works for me too!
