### ISSUE TITLE
empty character list vs. empty number list

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#202]
```
      ⍬≡1↓'a'
0
```

```
APRIL> (april "⍬≡1↓'a'")
1
```

[somewhere](https://www.youtube.com/watch?v=WlUHw4hC4OY) around the hour mark marshall said that dyalog remembers if a list is a chararcter list or a number list so i thought i'd test it out.

**Comment by justin2004** [comment]
```
... empty lists also kind of
64:39
store type information which
64:40
is called a prototype in [dyalog] so the
64:42
list of no numbers is actually different
64:44
from the [list of] no characters
```

**Comment by phantomics** [comment]
Fixed, the problem was actually with `↓`. It produced an empty numeric vector. Running `⍬≡''` produced 0 as it should.
