### ISSUE TITLE
identity element for the result of reduction

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#204]
that is, marshall says before the reduction is done the identity element of the result is computed (or looked up?) so the that result can be the identity element (when it needs to be -- like in this case).

```
      +⌿+⌿(⍳2)∘.× ⍬ ∘.× (⍳4)
0 0 0 0
```

```
APRIL> (april "+⌿+⌿(⍳2)∘.× ⍬ ∘.× (⍳4)")
#()
```

**Comment by justin2004** [comment]
```
 if you put
69:23
an empty list on the front of lists that
69:27
can't change the reduction and yet the
69:31
result of this reduction has to be the
69:34
same as the reduction of the empty list
69:38
applied with the function to the
69:40
reduction of the other list so the
69:45
result has to be the identity element 
```
https://www.youtube.com/watch?v=WlUHw4hC4OY&t=3146s

**Comment by phantomics** [comment]
This is now working correctly, try `(april "(×⌿,+⌿)+⌿(⍳2)∘.×⍬∘.×⍳4")`. When reduction turns an empty array into a non-empty array by eliminating 0-length axes, the identity value is used to populate the array.
