### ISSUE TITLE
possible optimization: when rank is used to apply a function on the last axis

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#208]
i think it might be safe to do this substitution...?
FL is a function that operates on the last axis
FF is the same function that operates on the first axis

replace occurrences of:
(FF⍤1) m 
with:
FL m

because using rank in this way does seem more expensive:
```
APRIL> (april "size←2000 ⋄ m← size size ⍴ ⍳size×size ⋄ 0")
0 
(time (april "⌽m ⋄ 0"))
APRIL> Evaluation took:
  0.079 seconds of real time
  0.574983 seconds of total run time (0.574983 user, 0.000000 system)
  727.85% CPU
  180,744,557 processor cycles                                     
  16,000,016 bytes consed
  
0
APRIL> (time (april "(⊖⍤1)m ⋄ 0"))
Evaluation took:
  6.024 seconds of real time                                       
  31.136338 seconds of total run time (31.003839 user, 0.132499 system)
  516.87% CPU
  13,830,369,292 processor cycles                                  
  40,587,056 bytes consed
                                                                   
0
```

**Comment by justin2004** [comment]
so that is about a 7,500% increase in runtime.

and in dyalog there is only about a 200% increase in runtime:
```
      )copy dfns cmpx
/opt/mdyalog/18.0/64/unicode/ws/dfns.dws saved Thu Jul 16 00:28:49 2020
      size←4 ⋄ m← size size ⍴ ⍳size×size ⋄ 0
0
      cmpx     '⌽m'      '(⊖⍤1)m'
  ⌽m     → 7.5E¯8 |    0% ⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕                            
  (⊖⍤1)m → 2.5E¯7 | +238% ⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕
```

so it seems like dyalog might have an optimization pattern in place.
but since they aren't identical runtimes in dyalog that makes me think maybe it isn't safe just to make the substitution without some checks.

**Comment by justin2004** [comment]
turns out there is basically no difference in dyalog (my size of 4 above was too small):
```
size←4000[ ](https://chat.stackexchange.com/transcript/message/60359049#60359049)⋄ m← size size ⍴ ⍳size×size
      cmpx     '⌽m'      '(⊖⍤1)m'
  ⌽m     → 8.8E¯3 |  0% ⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕
  (⊖⍤1)m → 8.9E¯3 | +1% ⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕⎕
```

also Adám says "⌽ and ⊖⍤1 is completely equivalent, and so too for all such pairs" and that is the case for all pairs of functions where one operates on the first axis and the other on the last axis.

**Comment by phantomics** [comment]
This is implemented, give it a try. There is now no difference in runtime. It required the addition of some new metadata for array functions that operate along an axis. Some more refactoring will be needed to get this fully compatible with reduce and scan compositions and some other things.

**Comment by phantomics** [comment]
The optimization is now in place for the functions `/ ⌿ , ⍪ ↑ ↓ ⌽ ⊖` and for functions composed with the operators `/ ⌿`. If there are any others where it could be of use let me know.
