### ISSUE TITLE
empty numeric vector (Zilde) and catenate

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#21]
`(april "⍬,4 5")`
evaluates to the vector `0 4 5` but in gnu apl and dyalog it evaluates to the vector `4 5` 

in gnu apl and dyalog
`⍬,4`
evaluates to the vector `4` since ⍬is an empty vector
but april signals that nil is not of type number.

but it looks like you can get something that works like zilde should with:

```
CL-USER> (april "(1↓0)")
#*
CL-USER> (april "(1↓0),4")
#(4)
CL-USER> (april "(1↓0),4 5")
#(4 5)
```

**Comment by phantomics** [comment]
Good find, turns out the catenate logic wasn't properly handling ⍬. It's fixed now.
