### ISSUE TITLE
each with a jotted function/operator

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#216]
while looking for a way to do this without using each two times
```
APRIL> (april "+/¨+/¨4 5×⊂3 3⍴⍳9")
#(180 225)
```

i tried
```
APRIL> (april "+/∘+/¨4 5×⊂3 3⍴⍳9")
#(#(12 24 36) #(15 30 45))
```

but dyalog doesn't like that:
```
      +/∘+/¨4 5×⊂3 3⍴⍳9
RANK ERROR
      +/∘+/¨4 5×⊂3 3⍴⍳9
       ∧
```

**Comment by phantomics** [comment]
This now throws an error. To see the root of the problem try `3+/3`. You're giving a left window argument to the `/`-composed function while the right argument isn't an array.
