### ISSUE TITLE
monadic rho on nested scalars

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#22]
this looks sensible
```
CL-USER> (april "⊂1 2 3")
#(#(1 2 3))
CL-USER> (april "⍴⊂1 2 3")
1
```

but gnu apl and dyalog treat `⊂1 2 3` as a scalar with respect to monadic rho.
e.g.
```
      (⊂1 2 3)
 1 2 3 
      ⍴(⊂1 2 3)

```
that is, the last expression does not evaluate to 1 it evaluates to the empty vector just like `⍴4` evaluates to the empty vector.

**Comment by phantomics** [comment]
Many changes have been made. Enclosing with `⊂` now produces a 0-rank array and several utility functions have been updated to support this. Also, `⍬` has been corrected to produce an empty vector and `⍴1 2 3` produces a 1-element vector instead of a scalar.

**Comment by justin2004** [comment]
the evaluation looks good but i think the printer might need an adjustment now?

```
CL-USER> (april-f "⍴⊂1 2 3")
#() 
CL-USER> (april-f "⊂1 2 3")
The value
  NIL
is not of type
  NUMBE
```
