### ISSUE TITLE
feature request: "constant"

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#220]
i don't appreciate how it can be useful but i'll open this issue for completeness sake.

```
      5⍨ 2 6
5
      7 (5⍨) 2 6
5
```

```
APRIL> (april "5⍨ 2 6")
#(2 6)
APRIL> (april "7 (5⍨) 2 6")
#(2 6)
```

**Comment by phantomics** [comment]
This is implemented. Required a bit of a grammar change to accommodate lexical operators that can take values as operands.
