### ISSUE TITLE
fork spelling

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#226]
this is a fork spelling of #225 

```
      0 1 2 3 4 5 6 7 (1⍳⍨>) 4
6
```

```
APRIL> (april "0 1 2 3 4 5 6 7 (1⍳⍨>) 4")
#(1 1 1 1 1 2 2 2)
```

but if you add parens april does the right thing:
```
APRIL> (april "0 1 2 3 4 5 6 7 (1(⍳⍨)>) 4")
6
```

**Comment by justin2004** [comment]
actually im not sure if that is a fork after all

**Comment by justin2004** [comment]
yeah, it is still a fork. the left tine can be an array.

**Comment by phantomics** [comment]
This is fixed.
