### ISSUE TITLE
Wrong macroexpansion of bracket indexing when coupled with Iterate

### ISSUE THREAD

**Issue by Le-Brut** [phantomics/april#227]
So, basically, bracket indexing works ok with loop, but not with iterate, because iterate eliminates (progns) which represent ";" in april internally. Even though this is an iterate bug, I thought it would be right to give a heads up on it here too, so that other users could be aware of it.

Full details:

https://gitlab.common-lisp.net/iterate/iterate/-/issues/21

**Comment by phantomics** [comment]
Thanks for finding this. Sounds like it should be fixed on `iterate`'s side, but if they're sluggish I can look into alternate ways of doing `;`, the iteration macro doesn't choke on `(let)` forms does it? Also, here's a more compact way to express the April code in your example: `(april:april-c "{⍵[1;]}" #2A((0 0)))`. The `(april-c)` macro can save you a lot of `:in`s if you just need to pass in a variable or two.

**Comment by justin2004** [comment]
@Le-Brut you are not carpenter brut, are you!?
or do you just like is music?

**Comment by Le-Brut** [comment]
@phantomics The let forms `(let ())` are left as is. There were some commits on their repo 3 months ago, so I think it's there's a chance they will look into it, but I don't want to be overly optimistic. Thanks for the tip on april-c, I will make sure to use it!

@justin2004 I just really dig his music, sorry : ) This was supposed to be a throwaway account for some stuff, but somehow I still happen to use it from time to time.

**Comment by phantomics** [comment]
I've swapped uses of `(progn)` in compiled code for a new macro called `(series)`... which is just an alias of `(progn)`. Can you try it and let me know if it works?

I tried looking at your issue for `iterate` again and it's completely gone. Did they just delete it? Doesn't inspire confidence that the maintainers will do anything about the problem.

**Comment by Le-Brut** [comment]
@phantomics there's been data loss:
```
our gitlab has experienced a data lossage  incident
        from 27 February.
<gendl> the repositories are intact but any gitlab database data, e.g. Issues,
        between 27 February and Yesterday, have apparently and unfortunately
        been lost.
```
I have refiled it: https://gitlab.common-lisp.net/iterate/iterate/-/issues/21
> I've swapped uses of (progn) in compiled code for a new macro called (series)
The way iterate operates is it macroexpands : D `locally' could be used instead (it seems to operate just like progn, except it may accept a declaration up front (which influences indentation in emacs)). (let ()) as you suggested before would work too.

**Comment by phantomics** [comment]
I'm now using a macro that expands to a `(let () ...)` form. I tried:

```lisp
(iter
  (for i below 5)
  (collect (april:april "(4 2⍴⍳8)[3;]")))
```

and it worked. By the way, the `:unformat-output` sub-parameter is deprecated and no longer does anything. Let me know if this change works for you.

**Comment by Le-Brut** [comment]
Yeah, it works! Thank you!
