### ISSUE TITLE
?(10 2⍴0) => error

### ISSUE THREAD

**Issue by some-mthfka** [phantomics/april#229]
```
The value
0.6680220056163343d0
is not of type
BIT
when setting an element of (ARRAY BIT)
```
 ?(10 2⍴1) works fine though

**Comment by phantomics** [comment]
The problem here is that `?0` yields a float between 0 and 1. I've pushed a change that will now create appropriate float or t-typed arrays for random numbers when the input array includes a 0.

**Comment by some-mthfka** [comment]
Thanks!
