### ISSUE TITLE
:unformat-output question

### ISSUE THREAD

**Issue by some-mthfka** [phantomics/april#230]
>  If you'd like to receive nested array output from April where the nested arrays are not wrapped in 0-rank scalar arrays, you can use the :unformat-output sub-parameter. 

It looks like the default is T, right? Anyway

```
(april (with (:state :unformat-output t))
       "+/1 (2 2⍴⊂0 1)")
```
produces `#0A#2A((#(1 2) #(1 2)) (#(1 2) #(1 2)))`

is this a bug or expected behavior?

> APL and Common Lisp use different models for nested arrays. [Read more about it here.](https://github.com/phantomics/april#differences-between-apl-and-common-lisp-nested-array-models)

the link doesn't seem to point to an existing place

**Comment by phantomics** [comment]
This documentation referred to a deprecated function and has been removed.

**Comment by some-mthfka** [comment]
Ok, understood!
