### ISSUE TITLE
@ has improper behavior with ∘

### ISSUE THREAD

**Issue by carkat** [phantomics/april#232]
```
f ← 'x'∘=
f 'asdfxasdf'
```
Works as intended, however
```
(' '@'x'∘=)'asdfxasdf'
```

says 'x' is not a number

**Comment by carkat** [comment]
This works in April:
https://cdn.discordapp.com/attachments/916489853804347442/967141109669171230/unknown.png



This works in Dyalog
```
day9←{
     ⎕IO←0 ⋄ o←'(' ⋄ c←')' ⍝ [o]pen [c]lose paren
     f←{
         0=≢⍵:0                    ⍝ empty ⍵
         o≠⊃⍵:1+∇ 1↓⍵            ⍝ first is not (enclosure)
         i←1+⍵⍳c                   ⍝ [i]ndex for end of first (enclosure)
         (t n)←⍎(' '@{'x'=⍵})i↑⍵   ⍝ [t]ake [n] repetitions
         s←t↑i↓⍵                   ⍝ [s]egment
         (n×⍺⍺ s)+∇(i+t)↓⍵
     }
     p1←≢  ⍝ count of each segment
     p2←{p2 f ⍵} ⍝ recursive expansion
     1-⍨(p1 f,p2 f)⍵ ⍝ why -1?
 }
```

**Comment by razetime** [comment]
An important rule to know in APL is that operators bind from left to right. so what's happening is `(( '@'x')∘=)` and errors on `'x'` not being a number. You need `' '@('x'∘=)`.

**Comment by phantomics** [comment]
The syntax appears to be implemented correctly in this case, so this issue is closed.
