### ISSUE TITLE
⎕IO tolerates values other than 0 or 1

### ISSUE THREAD

**Issue by faeredia** [phantomics/april#241]
environmental-symbols.md suggests ⎕IO is:
`The number from which counting begins; may be 1 (default) or 0.`
But:
```
> (april:april "⎕IO←5⋄⍳5")
#(5 6 7 8 9)
> (april:april (with (:state :count-from 5)) "⍳5")
#(5 6 7 8 9)
```

**Comment by phantomics** [comment]
April's current design goal is to allow for any `⎕IO`, and the environmental symbols list has been updated to reflect this. This may change in the future if the permissive `⎕IO` interferes with optimization.
