### ISSUE TITLE
reshape with an empty vector as the left argument

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#25]
in dyalog
```
(⍳0) ⍴ 5 6 7
```
evaluates to 5

but
```
CL-USER> (april "(⍳0)⍴ 7 8 9")
The value 
  #0A0
is not of type
  VECTOR
```

**Comment by phantomics** [comment]
Good find. Monadic `⍳` used to produce a 0-rank array when given a zero, now it returns an empty vector, and `⍴` will return the right argument's first row-major element when passed an empty vector. You can write `⍬⍴5 6 7` to get the same result.

Thanks for finding all these, are you working on a project with April?

**Comment by justin2004** [comment]
no problem. 

i am just doing the dyalog tutorial right now but once i am done i'd like to use april to write an OWL2 reasoner (https://en.wikipedia.org/wiki/Web_Ontology_Language).
 i wrote a junky reasoner in common lisp for hofstadter's MIU formal system (https://en.wikipedia.org/wiki/MU_puzzle) but i think it would be fun to do a reasoner in APL. and i need OWL2 reasoners for work so maybe a win win.

**Comment by phantomics** [comment]
Interesting, from what I can see it seems like an OWL reasoner is mainly concerned with semantic relationships, an area where I'd usually reach for Lisp before APL. Will your approach be based on processing graph data, i.e. representing graph connections between interconnected concepts as numeric matrices or something like that? Send an email to the address in my profile if you'd like to discuss it.
