### ISSUE TITLE
Bugfix in `count-cpus` on Windows

### ISSUE THREAD

**Issue by mirkov** [phantomics/april#256]
This is on Windows, MSYS2, SBCL, Emacs+Slime

`count-cpus` has a `case` statement. For Windows it selects on `:windows`. 

However `uiop:operating-system` returns two values: `:win` and `:windows`. 

When I change the case test from `:windows` to `:win`, April's demo runs fine. Otherwise it throws an error.

Ideally, there should be fall-through case and an exception handler that would point the user to the wisards behind April for help.

Mirko

**Comment by faeredia** [comment]
Bumped into this today porting code to windows

Consider using `serapeum:count-cpus` which covers more cases and accepts an argument for the default number of cpus on failure.
https://github.com/ruricolist/serapeum/blob/master/threads.lisp

**Comment by phantomics** [comment]
I'm now using `serapeum:count-cpus` to count available threads.
