### ISSUE TITLE
Trains are broken again

### ISSUE THREAD

**Issue by carkat** [phantomics/april#258]
![image](https://user-images.githubusercontent.com/29047264/198754773-6c5164f4-f245-4540-aad9-aadc4147ab33.png)
Dyalog train works fine
April produces incorrect results

![image](https://user-images.githubusercontent.com/29047264/198754778-b289e598-9594-4dfb-988b-e1c9d2499709.png)
April atop removed from the train produces correct results

**Comment by carkat** [comment]
```apl
   ∧/2(=⍥≢)/('asdf' 'asdf' 'asdf' 'asdf')
1
```
another instance where train doesn't work
```apl
   ∧/2{⍺(=⍥≢)⍵}/('asdf' 'asdf' 'asdf' 'asdf')
1
```

but explicit works

**Comment by phantomics** [comment]
This is fixed.
