### ISSUE TITLE
Strange  ⎕←'' behavior which has side-effects

### ISSUE THREAD

**Issue by carkat** [phantomics/april#259]
https://codeberg.org/CptJimKirk/aoc/src/commit/65902f25e5327e9d407ed76b3e4da3d235b202d5/cl/apl/15.apl#L96

There are two examples on this commit. Line 96 / 78

Removing the ⎕←⍵ or ⎕←'' respectively on these lines raises an error

![image](https://user-images.githubusercontent.com/29047264/199307209-f10b9a09-008d-47c7-8b36-2f0bd9d0ad8d.png)

Here is a screenshot, showing that removing the ⎕← on 96 raises this error. Same error if the ⎕← is removed from 78

**Comment by phantomics** [comment]
This should be resolved, let me know if any of these issues recur.
