### ISSUE TITLE
partitioned enclose doesn't scalar extend

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#26]
i don't think this is a migration level situation but i may be wrong about that.

in april
```
CL-USER> (april "1⊂⍳10")
#(#(1 2 3 4 5 6 7 8 9 10))
CL-USER> (april "⍴1⊂⍳10")
#*1
```

in dyalog
```
      1⊂ ⍳10
 1  2  3  4  5  6  7  8  9  10 
      ⍴1⊂ ⍳10
10
```
so dyalog scalar extends the 1 to evaluate to a 10 item vector

**Comment by justin2004** [comment]
another example of the scalar extension  from dyalog:
```
      1 ⊂ ⍳10
 1  2  3  4  5  6  7  8  9  10 
      1 1 1 1 1 1 1 1 1 1 ⊂ ⍳10
 1  2  3  4  5  6  7  8  9  10
```

**Comment by phantomics** [comment]
You're right, I overlooked extension for scalar right arguments to `⊂`. It's fixed now.
