### ISSUE TITLE
⍣ operator, non-deterministic and seems to create new scopes for each iteration?

### ISSUE THREAD

**Issue by carkat** [phantomics/april#260]
# Data does not persist / new scope per iteration?
[LINK TO OFFENDING CODE EXAMPLE](https://codeberg.org/CptJimKirk/aoc/src/commit/3034edcd842c69df66750115d26c61a348b1ccf6/cl/apl/15.apl#L99)

Here is a run that uses the power operator. As you can see on line 99, `rm` is called, which returns a table without the values of the first column in `accum`. This returns the same value as if I had called `parse¨table` a single time Calling multiple times accumulates more and more values into the table. 
### accumulation doesn't seem to persist
![image](https://user-images.githubusercontent.com/29047264/199307926-173dd525-aba5-4b6e-a0fb-36a3bcf3a6f6.png)

### accumulation should be persisting, except for the power operation?

This list will continue to populate as more values are accumulated. But you can see in the first screenshot the number of values remains constant, even with integer right operands to power. 

![image](https://user-images.githubusercontent.com/29047264/199308349-cc104ca4-545c-4df3-9e8d-2748e73a5cc5.png)

--------------------------------
# Non Determinism

To test the above I created a small example:

```
        accum←1 2⍴'default' 0
        update←{accum⍪←(⊃⍵) (⊃⌽⍵)}
        {_←{update 'new' ⍵}¨⍵⋄⌽¯1↓⍵}⍣5⊢⍳5
        accum
```
Output should be numbers bouncing from end of range to end of range, settling at the middle. 

![image](https://user-images.githubusercontent.com/29047264/199308758-3b19645e-12b4-4418-a9ff-4b6952fcde9d.png)

![image](https://user-images.githubusercontent.com/29047264/199308607-1a0143ce-b944-45e7-b4e2-cf406bc5e717.png)
Above are a few runs of day8. 

Below are the counts of several more runs, which produce different length results, despite being a deterministic algorithm. 
![image](https://user-images.githubusercontent.com/29047264/199309003-74799eae-8125-4501-ac65-a405af6f046d.png)

**Comment by phantomics** [comment]
This has been temporarily remedied by disabling threading for the ¨ operator. Threading for operators should be inhibited when they are given functions with side effects, but the logic for doing this is complicated. Stay tuned for a better solution to this issue.

**Comment by phantomics** [comment]
This has now been properly fixed. Functions defined within the scope of a function will now have side effects properly accounted for, and functions with side effects in such a scope will produce non-threaded functions with composed with operators like `¨`.
