### ISSUE TITLE
assignment in expressions causing unintended side-effects

### ISSUE THREAD

**Issue by carkat** [phantomics/april#261]
https://codeberg.org/CptJimKirk/aoc/src/commit/3034edcd842c69df66750115d26c61a348b1ccf6/cl/year.lisp#L11

`intp` and `pint` are  stored function passed into APRIL. In Dyalog, the equivalent would be something to the effect of

```
      intp←{(⍕⍵)≡⊃'\d+'⎕S{⍵.Match}⊢⍕⍵} ⍝ is an integer? 
      pint←{intp ⍵: ⍎⍵ ⋄⍵}                ⍝ parse integer
 ```
 
 In APRIL  was trying to inline assign intermediate expressions so I can use them in future expressions, ***but the following overwrote the function `intp`***
 
 ```
       X←intp x←pint '123'                                ⍝ an expression
      (X x)
1 123
      Y←intp y←pint '123'
      (Y y)
1 123
```

Notice in the expression, `intp` is a function and I'm assigning to either x or y, then passing the value x or y to the function `intp`. 

In April however, this expression overwrote `intp` with `(L.0)`. For one thing, in Dyalog one cannot reassign nameclasses. 

![image](https://user-images.githubusercontent.com/29047264/199311987-0bd88583-d6dd-45f8-ab9e-3b5fc5034b0e.png)

So I should not be able to overwite a function with a value. But also it is generally true that inline assignment should not assign to function names. 

```
x ⌽ y←double x←⌈/numbers
```
double shouldn't be overwritten, and neither should `⌽` or `x` in the leftmost expression.

**Comment by phantomics** [comment]
Attempting to overwrite functions with values and vice versa now causes an error.
