### ISSUE TITLE
inverse of a function with some indexing

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#264]
should april throw a domain error like dyalog does or should it be able to handle this?

```lisp
CL-USER> (april "{'ABC'[⍵]}2")
#\B
CL-USER> (april "({'ABC'[⍵]}⍣¯1)'B'")
NIL
```

```apl
      ({'ABC'[⍵]}⍣¯1)'B'
DOMAIN ERROR
      ({'ABC'[⍵]}⍣¯1)'B'
      ∧
```

**Comment by phantomics** [comment]
Interesting, it's a unique case for dfn inversion. You'll get a domain error when attempting to use `⌷⍣¯1` so perhaps that's what should happen in this case.

**Comment by phantomics** [comment]
This now returns an error, indexing is not possible in an inverted defn.
