### ISSUE TITLE
I use april-c to bind varible,however Cannot save core with multiple threads running.

### ISSUE THREAD

**Issue by secwang** [phantomics/april#266]
(sb-ext:save-lisp-and-die #p"my-app-binary" :toplevel #'b:run :executable t)

debugger invoked on a SB-IMPL::SAVE-WITH-MULTIPLE-THREADS-ERROR in thread
#<THREAD "main thread" RUNNING {1001090003}>:
  Cannot save core with multiple threads running.

  Interactive thread (of current session):
    #<THREAD "main thread" RUNNING {1001090003}>

  Other threads:
    #<THREAD "april-language-kernel" waiting on: # {1007A909B3}>,
    #<THREAD "april-language-kernel" waiting on: # {1007A90663}>,
    #<THREAD "april-language-kernel" waiting on: # {1007A916F3}>,
    #<THREAD "april-language-kernel" waiting on: # {1007A91053}>,
    #<THREAD "april-language-kernel" waiting on: # {1007A90D03}>,
    #<THREAD "april-language-kernel" waiting on: # {1007A913A3}>,
    #<THREAD "april-language-kernel" waiting on: # {1007A91A43}>,
    #<THREAD "april-language-kernel" waiting on: # {1007A91D93}>
See also:
  The SBCL Manual, Node "Saving a Core Image"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-IMPL::DEINIT)

**Comment by phantomics** [comment]
I tried this, is this similar to what you're doing?

```lisp
* (asdf:load-system 'april)

* (defvar bla (april:april-c "{⍵×⍳10}" 15))

* (defun dorun () (loop :for i :while t :do (sleep 0.1)))

* (sb-ext:save-lisp-and-die #p"/tmp/lbinary" :toplevel #'pkg:dorun :executable t)
```

Then I got the `sb-impl::save-error` but no language telling me that it was because of the multiple threads.

**Comment by secwang** [comment]
I tried to use april with postmorden. Here is my code.
The strange thing here is that if I load this code, it can be executed, so according to my experience, I think it can generally be build into exe.
```
(load "~/quicklisp/setup.lisp")

(ql:quickload '(postmodern april)  :silent t)

(defpackage :b (:use :cl :postmodern :april) (:export :run))
(in-package :b)

(defparameter cns '("postgres" "postgres" "password" "host"))


(defun list-to-2d-array (list)
  (make-array (list (length list)
                    (length (first list)))
              :initial-contents list))

(defun run ()
    (with-connection cns
      (let* ((a  (query "select * from table ;"))
	     (av (list-to-2d-array a)))
	(format t  "~A~%" (april-c "{[a]  +/ a[;6] > 0 }" av))
	(format t "~A~%" (april-c "{[a] +/ a[;6] < 0 }" av))
	(format t "~:d~%" (round (april-c "{[a] +/ a[;7] }" av)) )
	)))
```

**Comment by secwang** [comment]
> 

I regenerate error by follow code.
```
(asdf:load-system 'april)
(defvar bla (april:april-c "{⍵×⍳10}" 15))
(defun dorun () bla)  
(sb-ext:save-lisp-and-die "app" :toplevel #'dorun :executable t)
```
debugger invoked on a SB-IMPL::SAVE-WITH-MULTIPLE-THREADS-ERROR in thread
#<THREAD "main thread" RUNNING {10044601E3}>:
  Cannot save core with multiple threads running.

  Interactive thread (of current session):
    #<THREAD "main thread" RUNNING {10044601E3}>

  Other threads:
    #<THREAD "april-language-kernel" waiting on: # {1002DE89B3}>,
    #<THREAD "april-language-kernel" waiting on: # {1002DE8663}>,
    #<THREAD "april-language-kernel" waiting on: # {1002DE96F3}>,
    #<THREAD "april-language-kernel" waiting on: # {1002DE9053}>,
    #<THREAD "april-language-kernel" waiting on: # {1002DE8D03}>,
    #<THREAD "april-language-kernel" waiting on: # {1002DE93A3}>,
    #<THREAD "april-language-kernel" waiting on: # {1002DE9A43}>,
    #<THREAD "april-language-kernel" waiting on: # {1002DE9D93}>
See also:
  The SBCL Manual, Node "Saving a Core Image"

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

SBCL 2.2.11,  On OS X. Install april from quicklisp locally dir.

**Comment by phantomics** [comment]
I've been trying this myself but on Linux kernel 5.4.0-17.1 with SBCL 2.1.7 I just get:

```
Could not save core.
   [Condition of type SB-IMPL::SAVE-ERROR]
```

I can try updating the SBCL version and seeing if that works.

Also,. can you try running this as the last line in your test instead of the save-lisp-and-die and see what it returns?

```lisp
(loop :for worker :across (lparallel.kernel::workers lparallel::*kernel*) :collect (lparallel.kernel::running-category worker))
```

This will tell you if any threads in the system are busy; if not it should just return a list of NILs.

**Comment by secwang** [comment]
```
(loop :for worker :across (lparallel.kernel::workers lparallel::*kernel*) :collect (lparallel.kernel::running-category worker))
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                  {10044801E3}>:
  The value
    NIL
  is not of type
    LPARALLEL.KERNEL:KERNEL

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10044801E3}>
0: ((LAMBDA NIL :IN "/Users/secwang/tmp/a.lisp"))
1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LOOP :FOR WORKER :ACROSS (LPARALLEL.KERNEL::WORKERS LPARALLEL.KERNEL:*KERNEL*) :COLLECT (LPARALLEL.KERNEL::RUNNING-CATEGORY WORKER)) #<NULL-LEXENV>)
2: (SB-EXT:EVAL-TLF (LOOP :FOR WORKER :ACROSS (LPARALLEL.KERNEL::WORKERS LPARALLEL.KERNEL:*KERNEL*) :COLLECT (LPARALLEL.KERNEL::RUNNING-CATEGORY WORKER)) 8 NIL)
3: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (LOOP :FOR WORKER :ACROSS (LPARALLEL.KERNEL::WORKERS LPARALLEL.KERNEL:*KERNEL*) :COLLECT (LPARALLEL.KERNEL::RUNNING-CATEGORY WORKER)) 8)
4: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (LOOP :FOR WORKER :ACROSS (LPARALLEL.KERNEL::WORKERS LPARALLEL.KERNEL:*KERNEL*) :COLLECT (LPARALLEL.KERNEL::RUNNING-CATEGORY WORKER)) :CURRENT-INDEX 8)
5: (SB-C::%DO-FORMS-FROM-INFO #<FUNCTION (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {10001F534B}> #<SB-C::SOURCE-INFO {100108F833}> SB-C::INPUT-ERROR-IN-LOAD)
6: (SB-INT:LOAD-AS-SOURCE #<SB-SYS:FD-STREAM for "file /Users/secwang/tmp/a.lisp" {10001F2853}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
7: ((LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) #<SB-SYS:FD-STREAM for "file /Users/secwang/tmp/a.lisp" {10001F2853}> NIL)
8: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<FUNCTION (LABELS SB-FASL::LOAD-STREAM-1 :IN LOAD) {840F82B}> #<SB-SYS:FD-STREAM for "file /Users/secwang/tmp/a.lisp" {10001F2853}> NIL #<SB-SYS:FD-STREAM for "file /Users/secwang/tmp/a.lisp" {10001F2853}>)
9: (LOAD #<SB-SYS:FD-STREAM for "file /Users/secwang/tmp/a.lisp" {10001F2853}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT)
10: ((FLET SB-IMPL::LOAD-SCRIPT :IN SB-IMPL::PROCESS-SCRIPT) #<SB-SYS:FD-STREAM for "file /Users/secwang/tmp/a.lisp" {10001F2853}>)
11: ((FLET SB-UNIX::BODY :IN SB-IMPL::PROCESS-SCRIPT))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-11" :IN SB-IMPL::PROCESS-SCRIPT))
13: (SB-IMPL::PROCESS-SCRIPT "/Users/secwang/tmp/a.lisp")
14: (SB-IMPL::TOPLEVEL-INIT)
15: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
16: ((FLET "WITHOUT-INTERRUPTS-BODY-3" :IN SB-IMPL::START-LISP))
17: (SB-IMPL::%START-LISP)
```

**Comment by phantomics** [comment]
Thanks, looks like nothing's out of the ordinary in your threading kernel. I'll check into possible issues with SBCL and lparallel; for some reason I get the same `Could not save core.` error even if I try to save a bare system state just after starting up without loading April or any other package.

**Comment by phantomics** [comment]
I'm building 2.3.0 now, I'll see how it handles saving binaries.

**Comment by phantomics** [comment]
2.3.0 is built and I'm seeing the same error you do. Building binaries without April loaded is working. I'll see what I can find from this point.

**Comment by secwang** [comment]
good job

**Comment by phantomics** [comment]
Try putting this in a file and loading it:

```lisp
(asdf:load-system 'april)
(defvar bla (april:april-c "{⍵×⍳10}" 15))
(defun dorun () bla)
(lparallel::end-kernel :wait t)
(sb-ext:save-lisp-and-die "/tmp/app" :toplevel #'dorun :executable t)
```

The `(end-kernel)` will shut down all lparallel workers. This won't work if you do it from a REPL because there will be another kernel with Swank-related tasks still running.

**Comment by secwang** [comment]
It works , great work!

**Comment by phantomics** [comment]
Great, I'm interested to hear more about your April use case if possible. Let me know if there are any further issues.

**Comment by secwang** [comment]
At present, it is not of practical use. I'm learning apl/april/j/k and
rewriting the previous statistical scripts with them by the way. I
want to find a balance between writing speed and running speed, so
that it can be used for larger tasks. At present, let's take a look at
the design of april and use the cl library to do things. According to
the input, it is a very good design, and I like it very much. I have
used cl before.

**Comment by phantomics** [comment]
Interesting. If you encounter any situations where April seems particularly slow let me know, there are places where significant optimization is possible but it's a matter of finding these cases in order to make improvements.

**Comment by secwang** [comment]
Under my test, the same task, the compiled runtime is almost twice longer that of dyalogapl. If it is to explain execution, the quickload of cl will take more time. To be honest, I haven't found out why april is slow. The current conclusion is like this.

However, because I am familiar with cl, april is actually the most convenient apl to process input and output and refer to other array languge. The same task, in dyalogapl and k/q, needs to be very painfully built from the bottom and try various environmental problems. I think even if april is not the fastest apl, it is actually a space in engineering.

Another problem for me is that I still need time to learn apl. Personally, I think dyalog actually provides very good documentation and entry-level environment and development support because of their revenue models. This is a good place to learn apl. This may be a very difficult place for april as open source software. In fact, I don't think there are many people familiar with common lisp and array language in my background. April may need to provide more direct repl. Of course, this is a very good project. Thank you. Cheers.

**Comment by phantomics** [comment]
April now has a REPL mode for Emacs, see: https://github.com/phantomics/april/tree/master/aprepl

Let me know if the installation instructions there make sense. Once it's installed, you can enter `M-x aprepl` to enter the REPL. This is still alpha software, hence it's not mentioned in the main README.

April's core lexical functions and operators are almost exactly the same as Dyalog's so you can use Dyalog's user manual as a reference for April. [This section of the README](https://github.com/phantomics/april#unique-language-features-in-april) summarizes the main differences between Dyalog and April. April notably lacks Dyalog's control statements like `:If` but it includes k-style if statements as a more flexible alternative to guards.

I agree with you about the learning curve of Emacs and I have some ideas about how to create a better CL end-user experience. That's a whole different discussion but these videos of mine (https://vimeo.com/237947324) (https://vimeo.com/269495385) may provide some food for thought.

**Comment by secwang** [comment]
I noticed aprepl, and I just don't want to open my emacs. You have done
great work.

**Comment by justin2004** [comment]
@secwang I use April from a REPL in vim. Let me know if you'd like the details on how I do that.
