### ISSUE TITLE
WITH-OPEN-FILE And OPEN need to know the external format

### ISSUE THREAD

**Issue by Yehouda** [phantomics/april#270]
https://github.com/phantomics/april/blob/2f575c486f2ec69374425dd0b1e3bd8d61840153/vex/vex.lisp#L901

The target file in this case is in external-format utf-8, but there is no clear way to find this for the implemntation. It therefore needs to specify it by adding :external-format :utf-8. For example:
```
                      string (with-open-file (stream (eval string) :external-format :utf-8)
```

An even better approach is to have a macro like *with-apl-file** that looks like that:
```
(defmacro with-apl-file ((filename &rest options) &body body)
  `(with-open-file (,filename :external-format :utf-8 ,@options) ,@body)))
```
and then use it. That makes it easier to make chnages and to avoid forgetting the :external-format.

**Comment by phantomics** [comment]
This should be fixed now, see the `with-open-vex-file` macro added to vex.lisp.
