### ISSUE TITLE
Can someone check ((⍳ 4) -1) × 2 on april-20230618-git

### ISSUE THREAD

**Issue by mirkov** [phantomics/april#273]
I am trying to generate a sequence `0 2 4 6 ...` in my first attempt at April & APL.

First, I am able to get this sequence with: `¯2+2×⍳4`. So, I don't have a show-stopper.

Second, while I was experimenting on how to get there, I tried `((⍳ 4) -1) × 2`. This is what I am reporting on.

On Macbook + SBCL + april-20220707-git I get `0 2 4 6`. I also get this on `tryapl.org`

On Linux + SBCL + april-20230618-git I get `1 3 4 7`

I am reporting this as a possible bug. I will try to examine the lisp expressions on the two machines when I get the chance.

Thanks

**Comment by phantomics** [comment]
You found a bug in the lazy evaluation of `⍳`. It's been fixed.
