### ISSUE TITLE
:store-fun, unexpected argument

### ISSUE THREAD

**Issue by some-mthfka** [phantomics/april#276]
Hey, just noticed something else with :store-fun:

```
(april:april
 (with (:state :in ((a 10) (b 20)))
       (:store-fun (bool (lambda (x) (not (zerop x))))))
 "bool (a≡b)")
```

yields

```
The value
  #<VARRAY:VADER-COMPARE {100AB233E3}>
is not of type
  NUMBER
   [Condition of type TYPE-ERROR]

Restarts:
 0: [RETRY] Retry SLY mREPL evaluation request.
 1: [*ABORT] Return to SLY's top level.
 2: [ABORT] abort thread (#<THREAD tid=586505 "sly-channel-1-mrepl-remote-1" RUNNING {10015D8003}>)

Backtrace:
 0: (SB-KERNEL:TWO-ARG-= #<VARRAY:VADER-COMPARE {100AB233E3}> 0)
 1: (SB-VM::GENERIC-=)
 2: ((LAMBDA (X)) #<VARRAY:VADER-COMPARE {100AB233E3}>)
 3: ((LAMBDA ()))
 4: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APRIL:APRIL (WITH (:STATE :IN #) (:STATE :UNFORMAT-OUTPUT T) (:STORE-FUN #)) "bool (a≡b)") #<NULL-LEXENV>)
 5: (EVAL (APRIL:APRIL (WITH (:STATE :IN #) (:STATE :UNFORMAT-OUTPUT T) (:STORE-FUN #)) "bool (a≡b)"))
```

**Comment by phantomics** [comment]
This has been on my list of todos but I overlooked it until now. This happens because `vader-compare` is a virtual array object, a thunk that is part of the lazy eval system. April's internal functions know how to handle these but regular functions do not. I've fixed this by making imported functions always materialize their arguments. I may later add an option to import functions that won't automatically materialize arguments.

**Comment by some-mthfka** [comment]
@phantomics Thanks again, Andrew!

**Comment by phantomics** [comment]
Anytime, if you're building something with April I'd be interested to see it as you progress.

**Comment by some-mthfka** [comment]
@phantomics I use April for providing a math / linear algebra foundation for a GUI toolkit, called Fern, currently WIP. Since I don't expect users to know APL, I wrote [some wrappers](https://git.sr.ht/~project-mage/fern.linear-algebra/tree/master/item/src/main.lisp) (for the functions). So far only tested on some basic geometry stuff, it's looking good so far, and I think it's going to work out pretty great overall : )
