### ISSUE TITLE
division by zero on CCL

### ISSUE THREAD

**Issue by LdBeth** [phantomics/april#281]
```
(april:april "⎕DIV←1 ⋄ 1÷0")
```
gives division by zero error, and since the task is running on a separated thread, using `ccl:set-fpu-mode` cannot easily work.

**Comment by phantomics** [comment]
This is fixed, from what I can see it didn't have anything to do specifically with CCL or threading, I just didn't implement the case of dividing a left argument by 0 when `⎕DIV` is set to 1. That's working now.
