### ISSUE TITLE
Where (⍸) ignores elements other than 0 and 1

### ISSUE THREAD

**Issue by paulapatience** [phantomics/april#284]
```common-lisp
(april:april "⍸1 2 3") ; => #(1) (should be #(1 2 2 3 3 3))
(april:april "⍸¯1 0 1") ; => #(3) (should signal an error)
```

**Comment by phantomics** [comment]
This is fixed now, it applies `{(,⍵)/,⍳⍴⍵}` in the general case and uses its original optimized bit vector counting system in the case that the argument is determined to be a binary array.
