### ISSUE TITLE
index discloses when it should not?

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#33]
in dyalog the index function extracts the nested scalar 'bobby' but it does not disclose it (since its shape is an empty vector).
```
      bob ← 1 'bobby' (2 4) ⋄ ⍴bob[2]

```

if you want it disclosed you have to do it explicitly
```
      bob ← 1 'bobby' (2 4) ⋄ ⍴⊃bob[2]
5
```

but april discloses the indexed scalar too
```
APRIL> (april "bob←1 'bobby' (2 4) ⋄ ⍴bob[2]")
#(5)
```

**Comment by justin2004** [comment]
i think dyalog does not make the index function disclose because pick does indexing followed by disclose and april does it too
```
APRIL> (april "bob←1 'bobby' (2 4) ⋄ 2⊃bob")
"bobby"
```

**Comment by phantomics** [comment]
Interesting, I didn't notice this before. This is how that array is implemented in April:
```lisp
* (april "1 'bobby' (2 4)")
#(1 "bobby" #(2 4))
```

So nested arrays aren't wrapped inside a 0-rank array. This may reflect on the way that APL interpreters implement nested arrays. I'll think about this, in Lisp arrays can be nested within a t-type array without needing to have any structure wrapping them.

One solution could be to automatically enclose any non-rank-0 object that is retrieved by index from an array, with the pick function just returning them without enclosing. I'll try that and see how it works.

By the way, April differs from Dyalog's philosophy in that `[axes]` are not considered an operator, but a property of the function or object to their left. For lexical functions and operators they are considered a third function or operand; and unitary operators (currently only `$`) take no operands but may take axes. That's how I implemented the k-style `$[1;2;3]` if-statement within my APL paradigm.

**Comment by phantomics** [comment]
An update on this issue - it looks like I didn't understand the difference between APL's nested array model and Lisp's. In APL, all elements of an array must be scalars. That means that any nested array muse be wrapped in a 0-rank array. In Lisp that isn't the case, you can have arrays like #(1 2 #(3 4)).

The best way to address this will be to update April to the orthodox APL array model where any array that gets nested inside another is automatically enclosed. This will be a big change requiring some time and a separate source branch though.

**Comment by phantomics** [comment]
It's done, nested arrays in April are now always enclosed in rank-0 arrays. April's model is consistent with other APLs.
