### ISSUE TITLE
axes/index precedence

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#36]
this may be related to our discussion in #33 

it seems like in april the index glyph(s) is binding harder than the spaces that hold vectors together.

in dyalog the spaces that hold vectors together seem to bind harder:
```
      5 6 7 8[2]
6
```

```
APRIL> (april "5 6 7 8[2]")
Axes cannot be applied to numbers
```

**Comment by phantomics** [comment]
It's not related to #33 actually, this is a parser bug. Looking into it.

**Comment by phantomics** [comment]
This is fixed.
