### ISSUE TITLE
take assignment and drop assignment are not implemented

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#37]
that may be intentional so this might not be an issue?

in dyalog, first with scalar extension then without:
```
      v← 1 2 3 4 ⋄ (2↓v)←8 ⋄ v 
1 2 8 8
      v← 1 2 3 4 ⋄ (2↓v)←8 9 ⋄ v 
1 2 8 9
```
the same applies to take assignment

**Comment by justin2004** [comment]
when i was thinking about how these assignments could be implemented that reminded me of this funny thing i saw in dyalog.
i though you might find this interesting if you hadn't come across it yet.

```
      bob←⍴''
      ⍝ now bob has the shape of an empty character vector
      bob
0
      ⍝ bob looks like scalar zero
      bob=0
1
      ⍝ and bob is equal to zero but there is more to bob than that!
      ⍝ if bob was just zero then his rank should be 0 like the following:
      ⍴⍴0
0
      ⍝ but look at bob's rank
      ⍴⍴bob
1
      ⍝ it is curious that this is true (bob=0) but bob and 0 are not interchangeable under all operations
```

so bob isn't just a scalar zero he has some structure.

**Comment by justin2004** [comment]
oh, i am also just learning that there is compress assignment...

so there might be more still

**Comment by justin2004** [comment]
ok so it just looks like there are just 4 in total.
take, drop, compress, and pick.

here is dyalog doing the remaining two:
```
      ⍝ compress assignment
      v← 1 0 ¯7 6 ⋄ ((v<0) / v)← 9 ⋄ v
1 0 9 6
      ⍝ pick assignment
      v← 1 0 ¯7 6 ⋄ (2⊃v)←9 ⋄ v
1 9 ¯7 6
```

**Comment by phantomics** [comment]
You're right, this is called selective assignment and it's not yet implemented, I've been thinking about how to do it elegantly considering how the compiler works. I'd like to get in so I'll keep this issue around, but don't expect an implementation until later.

**Comment by phantomics** [comment]
One other thing about your bob example above: bob is a one-element vector of 0. The `⍴` function always returns a vector, even when its argument is one-dimensional. So `⍴⍴⍴x` doesn't quite equal 1 but a one-element vector of 1. If `⍴` returned a scalar when measuring the length of a vector, `⍴⍴⍴x` would be an empty vector, like you get when entering `⍴5`. When you evaluate `bob=0` you're not actually getting 1 back but a one-element vector of 1, just like you get a three-element vector of 1s when you evaluate `2=2 2 2`.

**Comment by justin2004** [comment]
ah, you're right. at the time i didn't appreciate that monadic rho always returns a vector.

**Comment by phantomics** [comment]
The four selective assignment functions are now implemented, let me know how it works for you.

**Comment by justin2004** [comment]
it is working for me. cool!
