### ISSUE TITLE
explicit vector precedence acts like enclose

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#38]
in dyalog
```
      ⍴2↓5 6 7 8
2
      ⍴(2↓5 6 7 8)
2
```
so i would say that dyalog just treats the parens like precedence enforcement not enclosure.

but i think april is enclosing in the second expression
```
APRIL> (april "⍴2↓5 6 7 8")
#(2)
APRIL> (april "⍴(2↓5 6 7 8)")
#*1
```

**Comment by phantomics** [comment]
That must have been related to the problem with `↓`, should be fixed. Try it again.

**Comment by justin2004** [comment]
the expression with drop works but i just noticed this (which i think is related):
```
APRIL> (april "cv←'apple bottom jeans' ⋄  'e'=cv")
#(0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0)
APRIL> (april "cv←'apple bottom jeans' ⋄  ('e'=cv)")
#(NIL)
```
but i don't think the parens should do anything

**Comment by phantomics** [comment]
It looks like my fix for empty spaces in axis sequences fixed this too. Try again and see how it works. It has to do with how the parser handles whitespace and closures.

**Comment by justin2004** [comment]
works for me now!
