### ISSUE TITLE
over taking a matrix with negative arguments (on the left)

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#40]
april over takes when you give positive arguments (on the left) and pads with zeros, as expected.

but it doesn't over take when you give negative arguments:
```
APRIL> (april-f "m←3 4 ⍴ ⍳20 ⋄ 2 ¯5↑m")
Invalid index 4 for axis 1 of (SIMPLE-ARRAY (UNSIGNED-BYTE 7)
                               (3 4)), should be a non-negative integer below 4
```

dyalog:
```
      m←3 4 ⍴ ⍳20 ⋄ 2 ¯5↑m
0 1 2 3 4
0 5 6 7 8
```

**Comment by phantomics** [comment]
This is fixed. I've rewritten the (section) function that powers `↑` and `↓` completely with better logic. It's now 32 lines vs. 77 lines for the old implementation, less than half the length.

**Comment by justin2004** [comment]
it feels snappier at the REPL ;)
