### ISSUE TITLE
April fails to print complex arrays (both 1-d and 2-d)

### ISSUE THREAD

**Issue by egao1980** [phantomics/april#41]
The code that aligns numbers by decimal dot assumes that (numberp ...) is comparable with 0 - not the case for complex numbers. 

Quick fix - use (realpart elem) and (realpart original) in the relevant parts of ARRAY-IMPRESS

**Comment by phantomics** [comment]
Good catch, look for that in the next commit. It's only a stopgap, though, correct complex printing will be a lot of work. From Dyalog:

```
      3 3⍴3.2J5.3 32.95J12.15
 3.20J05.3  32.95J12.15  3.20J05.3
32.95J12.15  3.20J05.3  32.95J12.15
 3.20J05.3  32.95J12.15  3.20J05.3
```

The Js and the dots are all lined up. I'll need to update (array-impress) to track 4 positions: the first dot, the J, the second dot and the end of the number.

**Comment by egao1980** [comment]
yep, and please note the 0-padded imaginary parts
Could we use CL fancy formatting instructions?

**Comment by phantomics** [comment]
(format) will make formatting the numbers easy, the hard part is counting the length of each segment in a column. I've been using a 2 x N array to store data for printing numbers, with N equal to the width of a printed array. The upper cell in each column holds the position of the dot on each row and the lower cell holds the total width of the row. I'll have to change this to a 4 x N array, with the four points being the positions of the first dot, the J, the second dot and the total width of the row.

**Comment by phantomics** [comment]
Good news! The printer has been completely overhauled; it now uses a system where printed columns can have varying numbers of segments. Decimal points and Js are aligned according to the length of a column's segments. Also, April has always used rational numbers internally but it now fully supports printing rational numbers, including rational numbers forming part of a complex number.

```lisp
*  (april-f "÷⍳5")
1 1r2 1r3 1r4 1r5
#(1 1/2 1/3 1/4 1/5)

* (april-f "⍪12.2J44 3r8J8r21 19r313J21r17")
12.200J44.0 
 3r008J08r21
19r313J21r17
#2A((#C(12.2 44.0)) (#C(3/8 8/21)) (#C(19/313 21/17)))
```

Give it a try and let me know what you think.

**Comment by egao1980** [comment]
Thanks! It's much better now. 
Few remaining issues:

```
(april:april-p "0 ¯1 ¯2 ¯6 ¯7 ∘.○ ¯2 ¯2J0")
0.0         J01.7320508 0.0         J01.7320508
¯1.57079640J01.3169578  ¯1.57079640J01.3169578 
 3.14159270J¯1.3169578   3.14159270J¯1.3169578 
 1.31695780J03.1415927   1.31695780J03.1415927 
¯0.54930615J01.5707964  ¯0.54930615J01.5707964 
```

- we need zero padding between real part and J
- some lookahead is needed to properly position lines prior the first minus sign

**Comment by egao1980** [comment]
It looks like imaginary part gets extra indent instead of real

**Comment by phantomics** [comment]
Good find, I'll look into that.

**Comment by phantomics** [comment]
The problem was actually with the logic for printing zero-value floats. That's now fixed, let me know if you find anything else.

One other thing. My printer works a bit differently from Dyalog's. Example:

```lisp
* (april-f "⍪12.2J44 3J8 19J210r17")
12.2J044.0 
 3  J008   
19  J210r17
#2A((#C(12.2 44.0)) (#C(3 8)) (#C(19 210/17)))
```

There's empty whitespace padding to the right of the integer components. It's not the best looking, but Dyalog seems render all complex parts as floats when placed in a column with complex floats. The 3 above would thus be represented as 3.0. I don't do this since the 3J8 number has integer components; they are not being coerced to floats. I'm not sure if Dyalog is inconsistent with their representations of numbers, I know that they use multiple types of integers and floats internally.
