### ISSUE TITLE
Minor: Reformat the code / use automatic formatter

### ISSUE THREAD

**Issue by egao1980** [phantomics/april#46]
Could we please use spaces in formatting? 

I'll look into providing automatic code formatting command to make code look consistent for all contributors. MOst likely it would be CLI emacs batch run :)

**Comment by justin2004** [comment]
> automatic code formatting command

it would be nice if it was an external (to the editor) command.
e.g. `xmllint --format`

**Comment by phantomics** [comment]
Can you detail a bit more the kind of formatting you'd prefer? More empty lines separating clauses within functions?

**Comment by phantomics** [comment]
It's not clear what kind of formatted changes are suggested, so I'm closing this for the time being. Feel free to open it again if you have specific suggestions.
