### ISSUE TITLE
index function on a matrix is too lenient?

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#48]
april gets the first row without the ';'
```
APRIL> (april "⎕←m←3 4 ⍴ ⍳13 ⋄ m[1]")
1  2  3  4
5  6  7  8
9 10 11 12
#(1 2 3 4)
```

but dyalog requires ';'
```
      m←3 4 ⍴ ⍳13 ⋄ m[1]
RANK ERROR
      m←3 4⍴⍳13 ⋄ m[1]
                   ∧
      m←3 4 ⍴ ⍳13 ⋄ m[1;]
1 2 3 4
```

**Comment by justin2004** [comment]
related

dyalog:
```
      m←3 4 ⍴ ⍳13 ⋄ m[2 2]
RANK ERROR
      m←3 4⍴⍳13 ⋄ m[2 2]
```

```
APRIL> (april-f "m←3 4 ⍴ ⍳13 ⋄ m[2 2]")
5 6 7 8
5 6 7 8
#2A((5 6 7 8) (5 6 7 8))
```

**Comment by mlochbaum** [comment]
There's precedence for the more lenient indexing in [A+](https://aplwiki.com/wiki/A%2B); see also this page on [leading axis theory](https://aplwiki.com/wiki/Leading_axis_theory).

**Comment by phantomics** [comment]
Marshall makes an interesting point but this "feature" was an oversight on my part. You can still use lenient indexing with the `[⌷ index]` function, I prefer for axis indexing to be explicit. Thanks for finding it.
