### ISSUE TITLE
drop on a matrix (shortcut?)

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#49]
```
APRIL> (april "m←3 4 ⍴ ⍳13 ⋄ 1 0↓m")
#2A((5 6 7 8) (9 10 11 12))
```

dyalog will do that too but dyalog will also do the same thing here (i don't know the name but it feels like a shortcut notation):
```
      m←3 4 ⍴ ⍳13 ⋄ 1↓ m
5  6  7  8
9 10 11 12
```

but april will not:
```
APRIL> (april "m←3 4 ⍴ ⍳13 ⋄ 1↓m") 
Incorrect number of dimensions to drop, 1, for input array of rank 2.
   [Condition of type SIMPLE-ERROR]
```

**Comment by phantomics** [comment]
Dyalog automatically pads the left argument with zeroes (for a drop) or the dimensions of the right argument (for a take) if the length of the left argument is less than the rank of the right argument. The (section) function now does the same thing.
