### ISSUE TITLE
(april (test))  : UNBOUND-VARIABLE OUT-STR

### ISSUE THREAD

**Issue by sts-q** [phantomics/april#5]
; in: APRIL:APRIL (TEST)
;     (APRIL:APRIL-P
;      "a←1 2 3 ⋄ ⎕ost←'OUT-STR' ⋄ ⎕←a+5 ⋄ ⎕←3 4 5 ⋄ ⎕ost←'OTHER-OUT-STR' ⋄ 3+a")
; --> APRIL:APRIL PROGN LET* APRIL::APL-ASSIGN SETQ 
; ==>
;   (THE T OTHER-OUT-STR)
; 
; caught WARNING:
;   undefined variable: OTHER-OUT-STR

; ==>
;   (THE T OUT-STR)
; 
; caught WARNING:
;   undefined variable: OUT-STR
; 
; compilation unit finished
;   Undefined variables:
;     OTHER-OUT-STR OUT-STR
;   caught 2 WARNING conditions
#########
#<UNBOUND-VARIABLE OUT-STR {1004557073}> 
#########

**Comment by phantomics** [comment]
The `out-str` and `other-out-str` symbols are now always interned in the April package.
