### ISSUE TITLE
padding item -- type and shape

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#51]
it looks like dyalog looks at the first vector item to determine what to pad with (its type and shape):
```
      v←'3' 2 1 ⋄ (4↑v)
3 2 1  
      v←('happy') 2 1 ⋄ (4↑v),'end'
 happy  2 1        end
      v← (1 2 3) 8 9 ⋄ (4↑v)
 1 2 3  8 9  0 0 0 
      v← (3 4 ⍴ ⍳13) 8 9 ⋄ (4↑v)
 1  2  3  4  8 9  0 0 0 0 
 5  6  7  8       0 0 0 0 
 9 10 11 12       0 0 0 0
```

while april always pads with a numeric scalar:
```
APRIL> (april-f "v← (3 4 ⍴ ⍳13) 8 9 ⋄ (4↑v)")
 1  2  3  4  8 9 0
 5  6  7  8
 9 10 11 12
#(#2A((1 2 3 4) (5 6 7 8) (9 10 11 12)) 8 9 0)
```

**Comment by phantomics** [comment]
Interesting, in my case I pad with spaces if it's a pure character array but anything else gets padded with zeroes.

**Comment by justin2004** [comment]
also in dyalog you can over take from empty vectors
```
      2↑⍬
0 0
      ' '=2↑''
1 1
```

**Comment by phantomics** [comment]
Changed the default fill behavior and enabled takes of empty vectors. Basing the fill on the first element seems questionable, though, I'm going to discuss it with others at some more length.

**Comment by justin2004** [comment]
i know the zero one infinity rule isn't intended to apply here but in a way it kind of does.
"The only reasonable numbers are zero, one and infinity."

since we must pad with something, selecting zero items to decide what to pad with won't work.
selecting all of the items to decide what to pad with leads to many more questions.
so selecting one, the first, is the only option.  :)

**Comment by phantomics** [comment]
I've decided that filling based on the first element is indeed the way to go. [This wiki article](https://aplwiki.com/wiki/Prototype) describes the concept of array prototyping and the rationale behind it. Prototypes are used in other functions like `⊃`, the subject of another issue I'll be addressing momentarily, so using the prototype system with `↑` makes functions more consistent.

**Comment by justin2004** [comment]
it looks like this one is still padding with 0.
```
CL-USER> (april-f "v← (3 4 ⍴ ⍳13) 8 9 ⋄ (4↑v)")
 1  2  3  4  8 9 0
 5  6  7  8
 9 10 11 12
#(#0A#2A((1 2 3 4) (5 6 7 8) (9 10 11 12)) 8 9 0
```

```
      v← (3 4 ⍴ ⍳13) 8 9 ⋄ (4↑v)
 1  2  3  4  8 9  0 0 0 0 
 5  6  7  8         0 0 0 0 
 9 10 11 12      0 0 0 0
```

did you mean to close this yet?

**Comment by phantomics** [comment]
Oh, interesting, the padding element is taken from the 0-value prototype of the entire initial nested array. I'll get that working.

**Comment by phantomics** [comment]
It works now.
