### ISSUE TITLE
indexing when nested scalars are involved

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#52]
dyalog
```
      (1 2 3 4) 15[1]
 1 2 3 4
```

when i looked at the marco expansion of this
```
APRIL> (april "(1 2 3 4) 15[1]")
#(#0A#(1 2 3 4) 15)
```
it was the same expansion as 
```
(april "(1 2 3 4) 15")
```

**Comment by phantomics** [comment]
Good find, this is fixed along with general improvements to inline vector indexing. Try `'a' 2[1] 2[1] 2[1] 2[1] 2[1]`.
