### ISSUE TITLE
reduce and scalars

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#54]
i haven't systematically found all all the functions that do this too but it looks like quite a few of them. here are a couple examples:
```
APRIL> (april "+/0")
The value
  -1
is not of type
  UNSIGNED-BYTE
```

```
      +/0
0
```

```
APRIL> (april "⌈/3")
The value
  -1
is not of type
  UNSIGNED-BYTE
```

```
      ⌈/3
3
```

**Comment by phantomics** [comment]
Fixed, scalar reduction now returns the argument.
