### ISSUE TITLE
simple-bit-vector return value 

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#56]
the second call to april evaluates to a simple-bit-vector so you can't do a lisp arithmetic comparison on it
```
APRIL> (= 4 (april "4"))
T
APRIL> (= 0 (april "⍴⍬"))
The value
  #*0
is not of type
  NUMBER
```
but shouldn't the second call to april just return a number?

**Comment by justin2004** [comment]
or should i just expect to need to (aref) ?

**Comment by justin2004** [comment]
actually i think i am wrong
```
      ⍴⍴⍬
1
```
it is a vector with 1 item

**Comment by phantomics** [comment]
You got it, `⍴` always returns a vector so `⍴` of a vector returns a 1-element vector. Otherwise `⍴⍴⍴X` would not equal one.
