### ISSUE TITLE
scan

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#57]
scan works in the demo
```
[\] Scan
  _ +\1 2 3 4 5
    1 3 6 10 1
```

but when i try it does not:
```
APRIL> (april "+\1 2 3 4 5")
#(1 2 3 4 5)
```

but scan first works for me:
```
APRIL> (april "+⍀1 2 3 4 5")
#(1 3 6 10 15)
```

this might just be on my end?

**Comment by justin2004** [comment]
also it looks like the minus sign is getting treated as monadic here:
```
APRIL> (april "-\25 3 2 4")
#(-25 -3 -2 -4)
```

instead of dyadic (alternating sums):
```
      -\25 3 2 4
25 22 24 20
```

**Comment by justin2004** [comment]
ah, i just noticed this helps:
```
APRIL> (april "+\\1 2 3")
#(1 3 6)
```

**Comment by phantomics** [comment]
You're right, the need to escape `\` can be counterintuitive. I've added language to the readme reminding users to do it.
