### ISSUE TITLE
dyadic ⍳ with scalar on the left

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#59]
dyalog won't accept a scalar on the left
```
      5⍳7
RANK ERROR
      5⍳7
       ∧
```

but april does:
```
APRIL> (april "5⍳7")
2
```

april's behavior there is kind of nice but we can also get that behavior with
```
APRIL> (april "(5,⍬)⍳7")
#(2)
```

**Comment by phantomics** [comment]
Scalar left arguments to `⍳` are allowed in GNU APL but discussion on `#apl` convinced me that a less lenient approach to functions like this is best. It's fixed. Also, all you need to use a single number on the left is `(,5)⍳7`.
