### ISSUE TITLE
parens

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#69]
i think this one is still at large:
https://github.com/phantomics/april/issues/38#issuecomment-706561139
EDIT: no, that works but it looks similar to this one.

dyalog:
```
     v←0 2⋄(v=0)
1 0
```

```
APRIL> (april "v←0 2⋄(v=0)")
#(NIL)
```

**Comment by phantomics** [comment]
Are you still having this problem? I just tried it: 

```lisp
* (april "v←0 2⋄(v=0)")
#(1 0)
```

**Comment by justin2004** [comment]
works for me now!

**Comment by phantomics** [comment]
Great, closing.
