### ISSUE TITLE
dyadic function trains

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#72]
i didn't see any dyadic function trains in the april demo.
so they might not be implemented?

dyalog
```
      ' ' (≠⊆⊢) ' one a  two'
 one  a  two
```

```
APRIL> (april "' ' (≠⊆⊢) ' one a  two'")
(LAMBDA (#:G521)) called with invalid number of arguments: 2
   [Condition of type SB-INT:SIMPLE-PROGRAM-ERROR]
```

**Comment by phantomics** [comment]
They're not implemented yet but I'll look into it.

**Comment by phantomics** [comment]
Dyadic functions trains are now in, give it a try.

**Comment by phantomics** [comment]
More good news: the use of inline and symbol-referenced functions in trains is now fully supported. Examples:

```lisp
* (april "(+ {⍺×⍵} -)5")
-25

* (april "' ' (∊{⍺,⍵[⍺],⍵}≠⊆⊢) ' one two  three'")
#(1 #0A"one" #0A"one" #0A"two" #0A"three")
```

**Comment by justin2004** [comment]
very cool!

though i don't understand the last expression. i thought trains could only have 3 functions (at most)?
but it does look like it evaluates to the same thing in dyalog. :)

**Comment by phantomics** [comment]
Trains can have any odd number of functions. Here's how the 2nd example works:

```
The output of ' ' (≠⊆⊢) ' one two  three' is #(#0A"one" #0A"two" #0A"three").

The output of ' ' ∊ ' one two  three' is 1.

The output of 1 {⍺,⍵[⍺],⍵} #(#0A"one" #0A"two" #0A"three") is #(1 #0A"one" #0A"one" #0A"two" #0A"three").
```

For each two extra functions you add to the end of the train, the left is applied to the original argument(s) and the right combines the result of the left with the result of the previous three train functions.
