### ISSUE TITLE
star diaeresis with right argument a negative number

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#78]
the temperature conversions example:
the negative 1 argument should make c the inverse of f.
```
      f←(32∘+)∘(×∘1.8)
      f 100
212
      c←f⍣¯1
      c 212
100
```

```
APRIL> (april "f←(32∘+)∘(×∘1.8)")
#<FUNCTION (LAMBDA (#:G3 &OPTIONAL #:G2)) {530E1B4B}>
APRIL> (april "f 100")
212.0
APRIL> (april "c←(f⍣¯1)")
#<FUNCTION (LAMBDA (#:G3 &OPTIONAL #:G2)) {530E205B}>
APRIL> (april "c 212")
212
```

**Comment by phantomics** [comment]
This is not implemented yet, it's quite complicated. I have given thought to how to do it and there are some structures in the language that should support implementing it, but it's a low priority for now.

**Comment by phantomics** [comment]
I've started work on implementing the negative power functionality. Currently it only works with single lexical functions, not with compositions like in the temperature converter example above. Example:

```lisp
* (april "1760 3 12⊥⍣¯1⊢82")
#(2 0 10)

* (april "2⋆⍣¯1⊢256")
8.0
```

There should be inverse versions working for most of the functions that can be inverted. In spec.lisp, you can look for functions whose specs contain an `(inverse)` form to see which ones I've created inverse versions of.

The next step is processing syntax trees and replacing the functions with their inversions. That will enable me to process compositions, and it may even allow me to invert arbitrary user-created defns, which APL interpreters can't do.

**Comment by justin2004** [comment]
cool!

> may even allow me to invert arbitrary user-created defns
wow. that is very neat!

> which APL interpreters can't do.
do APL interpreters not do it because they'd have to walk ASTs?

**Comment by phantomics** [comment]
Dyalog told me their operator implementations have no access to the syntax tree, so inverting a defn is impossible. Implementation of function inversion is now underway. Also, I've just reimplemented most of the operators to work primarily as runtime functions. This means that they can operate using function references that change at runtime, which the old system couldn't do. Each operator is still implemented with a macro to start with, though, so things like the `[$ if]` operator and the power operator inverting arbitrary functions are possible.

**Comment by phantomics** [comment]
I've created a draft implementation of the inversion functionality:

```lisp
* (april "⌊(32∘+)∘(×∘1.8)⍣¯1⊢212")
100
```
However, it still has many limitations. It supports compositions with `∘` but doesn't support `\`, ` ¨` or `⍨` yet, or internal uses of the power operator. Also, since it works as a macro, you can't plug a function designed elsewhere into it. I have a plan to address this but it'll require an unusual approach.

**Comment by phantomics** [comment]
Update: a good deal of Dyalog's `⍣¯x` inversion functionality is now working. Many functions have working inverse variants, and the inversion of functional expressions including the `∘`, `\`, `∘.`, `¨` and `⍨` operators, along with the power operator `⍣` itself, is now supported. I am now storing the inverse variants of defined functions alongside them, so you can invert a defined function. Check the [function inversion tests](https://github.com/phantomics/april/blob/master/spec.lisp#L1329) to see examples of what's working.

Development of this feature will be ongoing for some time, as there are many use cases to account for. I'll see if I can implement inversion for some defns; there will have to be a fairly strict set of criteria to qualify defns that can be inverted.

**Comment by phantomics** [comment]
Some progress on defn inversion:
```lisp
* (april "{5×2+⍵}⍣¯1⊢20")
2

* (april "{2*1+7-⍵}⍣¯1⊢64")
2.0
```

The functions you give it have to be quite linear with no left arguments and only one statement, but it's a start.

**Comment by phantomics** [comment]
I've implemented inversion of dyadic defns. Try `(3 {⍵+÷-⍺}⍣¯1⊢5), 3 {⍺+÷-⍵}⍣¯1⊢5`. You can currently only invert a function with a single instance of either argument, if there are multiple ⍵s or ⍺s it won't work. There will be more corner cases to consider but for now I'm calling the negative power functionality complete.
