### ISSUE TITLE
star diaresis with right argument a variable

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#85]
```
      (2 2⍴⍳4) {(↓⍣⍵)⍺} 1
 1 2  3 4 
      (2 2⍴⍳4) {(↓⍣⍵)⍺} 2
  1 2  3 4  
      (2 2⍴⍳4) {(↓⍣⍵)⍺} 3
   1 2  3 4
```

april can do it with a numeric literal as the right argument:
```
APRIL> (april-f "(2 2⍴⍳4) {(↓⍣1)⍺} 1")
 1 2  3 4
#(#0A#(1 2) #0A#(3 4))
APRIL> (april-f "(2 2⍴⍳4) {(↓⍣2)⍺} 1")
  1 2  3 4
#0A#(#0A#(1 2) #0A#(3 4))
APRIL> (april-f "(2 2⍴⍳4) {(↓⍣3)⍺} 1")
 1 2  3
#0A#0A#(#0A#(1 2) #0A#(3 4)
```

but not with a variable:
```
APRIL> (april-f "(2 2⍴⍳4) {(↓⍣⍵)⍺} 1")
The variable APRIL-WORKSPACE-COMMON::⍵ is unbound.
```

**Comment by phantomics** [comment]
This is fixed, `⍵` and `⍺` weren't being handled properly by the code composing operators. However, your examples also demonstrate there is a problem with printing nested vectors; look what happened with the printing in your April example above. I'm leaving this open until that's fixed too.

**Comment by phantomics** [comment]
The printer has been fixed to handle this case. Also, your code above can be more succinctly written as `↓⍣3⊢2 2⍴⍳4`.

```lisp 
* (april-f "↓⍣3⊢2 2⍴⍳4")
   1 2  3 4
#0A#0A#(#0A#(1 2) #0A#(3 4))
```

**Comment by justin2004** [comment]
i started watching Marshall Lochbaum's video on reduction and he used ⊢ in an expression in the same way. so i had to look it up.

in case anyone else is following along:
```
Notice that it is necessary to prevent the right operand k binding to the right argument. This can be done using parentheses e.g. (f⍤1)Y. The same can be achieved using ⊢ e.g. f⍤1⊢Y because ⍤ binds tighter to its right operand than ⊢ does to its left argument, and ⊢ therefore resolves to Identity.
```
https://help.dyalog.com/18.0/Content/Language/Primitive%20Operators/Rank.htm
