### ISSUE TITLE
rounding?

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#88]
not sure what is happening here but i wanted to note it before i forget
```
      10|21010111
1
      10.0|21010111
1
```

```
CL-USER> (april "10|21010111")
1
CL-USER> (april "10.0|21010111")
2.0
```

**Comment by phantomics** [comment]
Interesting, `|` passes right through to CL's (mod) function. Here's what that does:

```lisp
* (mod 21010111 10)
1

* (mod 21010111 10.0)
2.0
```

I'll check into the reasons for this.

**Comment by justin2004** [comment]
in python
```
In [27]: 21010111%10
Out[27]: 1

In [28]: 21010111%10.0
Out[28]: 1.
```

**Comment by phantomics** [comment]
This works better:

```lisp
* (mod 21010111 10.0d0)
1.0d0
```

Got a hint from comp.lang.lisp that it has to do with the 10.0 being a single-precision float. When you enter a floating point with no "d" in CL, it's interpreted as single-precision, the same carries over for April. The size of other argument to (mod) is the determining factor here.

This highlights an interesting contrast between APL and CL; in APL, there isn't a way to designate what type of float to pass as an argument. The implementation and representation of numbers is kind of vague in APL. You can see this in Dyalog when you create a matrix with complex floats and complex integers in the same column; the integers are represented with decimal points and trailing zeroes as if they were floats. I'll be looking into this more to determine best practices.

**Comment by phantomics** [comment]
April now uses double-floats internally, in keeping with the standard for current APL implementations. Evaluating `10.0|21010111` will return `1.0d0`.
