### ISSUE TITLE
assignment mid-expression within outer use

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#92]
i'm not sure how often people like to do this sort of thing but...

```
      apple[⍋apple←1 8 4 2]
1 2 4 8
```

```
APRIL> (april "apple[⍋apple←1 8 4 2]")
The value
  3
is not of type
  BIT
```

but on the second evaluation: 
```
APRIL> (april "apple[⍋apple←1 8 4 2]")
#(1 2 4 8)
```

**Comment by phantomics** [comment]
Here you're running into the limits of an APL compiler compared to an interpreter. The compiled code doesn't know how to handle apple's value here; an interpreter has the value by the time the apple[ ... ] is evaluated. I'll see if there's any way this could be made to work.

**Comment by phantomics** [comment]
It's working! The workaround I implemented is particular to indexing, so it won't allow for other types of mid-expression assignments, if you find any cases of such assignments file an issue, and let me know how this addition works for you.
