### ISSUE TITLE
selective assignment (involving a disclose)

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#93]
```
      apple←3 ⍴ ⊂⍳4 ⋄ (1↑⊃apple[1])←99 ⋄ apple
 99 2 3 4  1 2 3 4  1 2 3 4
```

```
APRIL> (april "apple←3 ⍴ ⊂⍳4 ⋄ (1↑⊃apple[1])←99 ⋄ apple")
Execution of a form compiled with errors.
```

**Comment by phantomics** [comment]
Oh, interesting. This is selective assignment using a combination of the valid selective assignment functions. It should be possible to get this in, I'm working on some other stuff in the meantime.

**Comment by phantomics** [comment]
The case above is working now. I've tested some more complex selective assignment forms and found them to work; some are now present in the tests. If you can find any more selective assignment forms that should work but don't, feel free to repoen this.
