### ISSUE TITLE
operator definitions

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#98]
i just learned you can define operators in dyalog (that reference their operand functions):
```
      my_operator←{⍺⍺ ⍵}
      ÷ my_operator 5
0.2
```

```
APRIL> (april "my_operator←{⍺⍺ ⍵}")
#<FUNCTION (LAMBDA (⍵ &OPTIONAL ⍺)) {53168DBB}>
APRIL> (april "÷  my_operator 99")
The variable APRIL-WORKSPACE-COMMON::⍺⍺ is unbound
```

https://help.dyalog.com/18.0/#Language/Defined%20Functions%20and%20Operators/DynamicFunctions/Dynamic%20Operators.htm

**Comment by phantomics** [comment]
Correct, operator definition is not yet supported in April. I'll look into it after some other things are out of the way.

**Comment by phantomics** [comment]
Your Christmas present is one day late. Operator definitions are now working. [See test examples here.](https://github.com/phantomics/april/blob/master/spec.lisp#L1335) Give them a spin and let me know how they work with those functions you're transcribing.

**Comment by justin2004** [comment]
i am trying to work around this now.

it handles an operator that has been assigned but not a literal operator
```
CL-USER> (april "myo←{⍺⍺ ⍵}")                                       
#<FUNCTION (LAMBDA (⍺⍺)) {53025B5B}>                                
CL-USER> (april "(⊃∘5 6 7) myo 2")                                  
6
CL-USER> (april "(⊃∘5 6 7){⍺⍺ ⍵}2")                                 
2
```


```
      (⊃∘5 6 7){⍺⍺ ⍵}2
6
```

**Comment by phantomics** [comment]
Correct, they're not working inline yet. That's coming soon, along with the ability for the user-defined operators to take operands with axes.

**Comment by justin2004** [comment]
i am still working through porting/transcribing some of the graph functions from dyalog. i am having trouble with getting the operator to work and i think this is related to my trouble:

```
      aop←{⍵⍵ 7}
      (1,5) aop - 1
¯7
```

```
CL-USER> (april "aop←{⍵⍵ 7}")
#<FUNCTION (LAMBDA (⍵⍵)) {5303689B}>
CL-USER> (april "(1,5) aop - 1")
invalid number of arguments: 2
```

**Comment by phantomics** [comment]
Interesting, usually having a `⍵⍵` means that the operator must take two operands, since only a pivotal operator will have a right argument represented by ⍵⍵. I'll look into that, in the mean time, my rebuild of the grammar system is now bearing fruit. Inline lateral operators are now working. Try `× {8 ⍺⍺ 5×2+⍵} 5`.

**Comment by phantomics** [comment]
Inline user-defined operators are now fully working; try `2-{(⍵ ⍵⍵ ⍺) ⍺⍺ (⍺ ⍵⍵ ⍵)}≤⊢3` for a pivotal operator. Let me know if you find anything still not working when transcribing Dyalog library functions.
