### ISSUE TITLE
function self reference with ∇

### ISSUE THREAD

**Issue by justin2004** [phantomics/april#99]
```
      fib←{(⍵=1)∨⍵=2:1 ⋄ (∇ (⍵-2))+∇ (⍵-1)}
      fib¨⍳7
1 1 2 3 5 8 13
```

```
APRIL> (april "fib←{$[(⍵=1)∨⍵=2;1;(∇ (⍵-2))+∇ (⍵-1)]}")
#<FUNCTION (LAMBDA (⍵ &OPTIONAL ⍺)) {531622FB}>
APRIL> (april "fib¨⍳7")
The value
  #\NABLA
is not of type
  NUMBER
```

of course this works
```
APRIL> (april "fib←{$[(⍵=1)∨⍵=2;1;(fib (⍵-2))+fib (⍵-1)]}")
#<FUNCTION (LAMBDA (⍵ &OPTIONAL ⍺)) {5317A50B}>
APRIL> (april "fib¨⍳7")
#(1 1 2 3 5 8 13)
```

at the moment i don't think this is that important because when i want to port something from dyalog to april i already have to do the conversion to the k-style if that april uses. but this issue would become more relevant if april would also recognize the dyalog guard syntax (if with ":") -- like in the first expression:

```
fib←{(⍵=1)∨⍵=2:1 ⋄ (∇ (⍵-2))+∇ (⍵-1)}
```

eventually i would love to pull into an april session the "dyalog standard library"-ish stuff:
http://dfns.dyalog.com/n_contents.htm

e.g. in dyalog if you want to use the path function from dfns.dyalog.com you just:
```
'path'⎕cy'dfns'
```
then path is in your workspace for use.

**Comment by justin2004** [comment]
oh, this actually turns out to be more useful than i originally thought.
without it you cannot do anonymous functions that are recursive.

e.g.
```
      {⍵=0:1⋄ ⍵×∇(⍵-1)}¨1 2 3 
1 2 6
```

**Comment by phantomics** [comment]
That's right. CL doesn't have a `this` like in Javascript, so I'm considering options to make this work elegantly.

**Comment by phantomics** [comment]
This is now working, try the Fibonacci sequence from above. Let me know if you encounter any problems using it.
